In [ ]:
import numpy as np
from itertools import 

# 惰性求值 大型数据集的生成器

In [1]:
sum(map(lambda i: i*i, range(1000000000)))

333333332833333333500000000

# 二维列表展开

In [20]:
A = [['a','b'],['c','d'],['e','f'],['g']]
[j for i in range(len(A)) for j in A[i]]

['a', 'b', 'c', 'd', 'e', 'f', 'g']

# 面定义一个圆，可以通过元组对应的名字来访问对应的值，下面访问圆的圆心坐标和半径

In [57]:
from collections import namedtuple
circle = namedtuple("Circle", ["x", "y", "r"])
circle1 = circle(2,4,6)
circle1,circle1.x,circle1.y,circle1.r

(Circle(x=2, y=4, r=6), 2, 4, 6)

#  元素计数

In [58]:
from collections import Counter
Counter('abcdeabcdabcaba')


Counter({'a': 5, 'b': 4, 'c': 3, 'd': 2, 'e': 1})

# 一维列表升二维


In [46]:
def group_adjacent(a, k): 
    return list(zip(*([iter(a)] * k)))

In [48]:
group_adjacent(['a', 'b', 'c', 'd', 'e', 'f'],2)

[('a', 'b'), ('c', 'd'), ('e', 'f')]

# 2-50内的质数(嵌套列表推导)
## 合数一般都是2-7的倍数
## 4是最小的合数，找出50以内的所有合数

In [21]:
[x for x in range(3,50) if x not in [j for i in range(2,8) for j in range(i*2,50,i)]]

[3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47]

# 全排列

In [32]:
B = [4,7,8,9]
np.array(list({(i,j) for i in B for j in B}))

array([[9, 7],
       [4, 7],
       [4, 9],
       [4, 8],
       [9, 8],
       [4, 4],
       [7, 7],
       [9, 9],
       [7, 4],
       [8, 9],
       [8, 8],
       [8, 7],
       [8, 4],
       [9, 4],
       [7, 8],
       [7, 9]])

# 组合

In [38]:
np.array(list({tuple(sorted((i,j))) for i in B for j in B}))

array([[4, 7],
       [4, 9],
       [4, 8],
       [4, 4],
       [7, 7],
       [9, 9],
       [8, 9],
       [8, 8],
       [7, 8],
       [7, 9]])

# 创建一个8x8矩阵，并用棋盘图案填充它（★☆☆）## 创建一个8x8矩阵，并用棋盘图案填充它（★☆☆）

In [39]:
import numpy as np
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 何获取昨天，今天和明天的日期？## 何获取昨天，今天和明天的日期？

In [40]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
yesterday,today,tomorrow

(numpy.datetime64('2020-06-17'),
 numpy.datetime64('2020-06-18'),
 numpy.datetime64('2020-06-19'))

# 获取与2016年7月对应的所有日期？

In [42]:
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


## 创建一个结构化网格，x和y坐标覆盖[0,1] x [0,1]区域

In [43]:
Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


# 判断给定的2D数组是否有空列

In [44]:
Z = np.random.randint(0,3,(3,10))
print((~Z.any(axis=0)).any())
Z

False


array([[0, 2, 0, 2, 1, 2, 2, 0, 0, 0],
       [0, 1, 0, 2, 2, 2, 1, 0, 1, 1],
       [2, 2, 2, 0, 1, 2, 2, 1, 1, 1]])

# 随机选择列表中的样本

In [1]:
import random
my_list = ['a', 'b', 'c', 'd', 'e']
num_samples = 2
samples = random.sample(my_list,num_samples)
print(samples)

['c', 'd']


# 展开列表

In [2]:
def flatten(l):
	return [item for sublist in l for item in sublist]
l = [[1,2,3],[3]]
flatten(l)

[1, 2, 3, 3]

In [1]:
from iteration_utilities import deepflatten
l = [[1,2,3],[4,[5],[6,7]],[8,[9,[10]]]]
list(deepflatten(l, depth=3))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [25]:
from collections.abc import Iterable

def flatten(input_arr, output_arr=None):
    if output_arr is None:
        output_arr = []
    for ele in input_arr:
        if isinstance(ele, Iterable): # 判断ele是否可迭代
            flatten(ele, output_arr)  # 尾数递归
        else:
            output_arr.append(ele)    # 产生结果
    return output_arr

flatten([[1,2,3],[4,5]], [6,7]) # [6, 7, 1, 2, 3, 4, 5]

[6, 7, 1, 2, 3, 4, 5]

# 将list等分为子组(生成器版)

In [3]:
from math import ceil
def divide_iter(lst, n):
    if n <= 0:
        yield lst
        return
    i, div = 0, ceil(len(lst) / n)
    while i < n:
        yield lst[i * div: (i + 1) * div]
        i += 1


In [4]:
list(divide_iter([1, 2, 3, 4, 5], 0))  # [[1, 2, 3, 4, 5]]

[[1, 2, 3, 4, 5]]

In [5]:
list(divide_iter([1, 2, 3, 4, 5], 2))  # [[1, 2, 3], [4, 5]]

[[1, 2, 3], [4, 5]]

# 批量转化驼峰格式

In [6]:
import re
def camel(s):
    s = re.sub(r"(\s|_|-)+", " ", s).title().replace(" ", "")
    return s[0].lower() + s[1:]

# 批量转化
def batch_camel(slist):
    return [camel(s) for s in slist]

batch_camel(['student_id', 'student\tname', 'student-add']) 

['studentId', 'studentName', 'studentAdd']

In [8]:
#1 爬取天气数据并解析温度值

#素材来自朋友袁绍

import requests
from lxml import etree
import pandas as pd
import re

url = 'http://www.weather.com.cn/weather1d/101010100.shtml#input'
with requests.get(url) as res:
    content = res.content
    html = etree.HTML(content)
#通过lxml模块提取值，lxml比beautifulsoup解析在某些场合更高效

location = html.xpath('//*[@id="around"]//a[@target="_blank"]/span/text()')
temperature = html.xpath('//*[@id="around"]/div/ul/li/a/i/text()')
print(location)
df = pd.DataFrame({'location':location, 'temperature':temperature})
print('温度列')
print(df['temperature'])

['香河', '涿州', '唐山', '沧州', '天津', '廊坊', '太原', '石家庄', '涿鹿', '张家口', '保定', '三河', '北京孔庙', '北京国子监', '中国地质博物馆', '月坛公园', '明城墙遗址公园', '北京市规划展览馆', '什刹海', '南锣鼓巷', '天坛公园', '北海公园', '景山公园', '北京海洋馆']
温度列
0     20/34°C
1     19/33°C
2     19/33°C
3     21/34°C
4     22/34°C
5     21/34°C
6     15/31°C
7     20/34°C
8     18/33°C
9     17/32°C
10    18/34°C
11    20/34°C
12    19/34°C
13    19/34°C
14    19/34°C
15    19/34°C
16    19/34°C
17    21/33°C
18    19/34°C
19    19/34°C
20    21/33°C
21    21/33°C
22    21/33°C
23    19/34°C
Name: temperature, dtype: object


In [9]:
df['high'] = df['temperature'].apply(lambda x: int(re.match('(-?[0-9]*?)/-?[0-9]*?°C', x).group(1) ) )
df['low'] = df['temperature'].apply(lambda x: int(re.match('-?[0-9]*?/(-?[0-9]*?)°C', x).group(1) ) )
print(df)

location temperature  high  low
0         香河     20/34°C    20   34
1         涿州     19/33°C    19   33
2         唐山     19/33°C    19   33
3         沧州     21/34°C    21   34
4         天津     22/34°C    22   34
5         廊坊     21/34°C    21   34
6         太原     15/31°C    15   31
7        石家庄     20/34°C    20   34
8         涿鹿     18/33°C    18   33
9        张家口     17/32°C    17   32
10        保定     18/34°C    18   34
11        三河     20/34°C    20   34
12      北京孔庙     19/34°C    19   34
13     北京国子监     19/34°C    19   34
14   中国地质博物馆     19/34°C    19   34
15      月坛公园     19/34°C    19   34
16   明城墙遗址公园     19/34°C    19   34
17  北京市规划展览馆     21/33°C    21   33
18       什刹海     19/34°C    19   34
19      南锣鼓巷     19/34°C    19   34
20      天坛公园     21/33°C    21   33
21      北海公园     21/33°C    21   33
22      景山公园     21/33°C    21   33
23     北京海洋馆     19/34°C    19   34


# 4 求字典前n个最大值

In [11]:
from heapq import nlargest

# 返回字典d前n个最大值对应的键
def topn_dict(d, n):
    return nlargest(n, d, key=lambda k: d[k])

topn_dict({'a': 10, 'b': 8, 'c': 9, 'd': 10}, 3)  # ['a', 'd', 'c']

['a', 'd', 'c']

# 5 求最小键值对

In [12]:
d={'a':-10,'b':5, 'c':3,'d':5}
min(d.items(),key=lambda x:x[1]) #('a', -10)

('a', -10)

# 1 字典值最大的键值对列表

In [14]:
def max_pairs(dic):
    if len(dic) == 0:
        return dic
    max_val = max(map(lambda v: v[1], dic.items()))
    return [item for item in dic.items() if item[1] == max_val]

max_pairs({'a': -10, 'b': 5, 'c': 3, 'd': 5})# [('b', 5), ('d', 5)]


[('b', 5), ('d', 5)]

# 2 字典值最小的键值对列表

In [16]:
def min_pairs(dic):
    if len(dic) == 0:
        return []
    min_val = min(map(lambda v: v[1], dic.items()))
    return [item for item in dic.items() if item[1] == min_val]
min_pairs({}) # []

r = min_pairs({'a': -10, 'b': 5, 'c': 3, 'd': 5})
print(r)  # [('b', 5), ('d', 5)]

[('a', -10)]


# 3 合并两个字典

In [18]:
def merge_dict(dic1, dic2):
    return {**dic1, **dic2}  # python3.5后支持的一行代码实现合并字典

merge_dict({'a': 1, 'b': 2}, {'c': 3})  # {'a': 1, 'b': 2, '

{'a': 1, 'b': 2, 'c': 3}

# 16 浮点数等差数列

In [19]:
def rang(start, stop, n):
    start,stop,n = float('%.2f' % start), float('%.2f' % stop),int('%.d' % n)
    step = (stop-start)/n
    lst = [start]
    while n > 0:
        start,n = start+step,n-1
        lst.append(round((start), 2))
    return lst

rang(1, 8, 10) # [1.0, 1.7, 2.4, 3.1, 3.8, 4.5, 5.2, 5.9, 6.6, 7.3, 8.0]

[1.0, 1.7, 2.4, 3.1, 3.8, 4.5, 5.2, 5.9, 6.6, 7.3, 8.0]

# 14 求列表中所有重复元素

In [20]:
from collections import Counter

def find_all_duplicates(lst):
    c = Counter(lst)
    return list(filter(lambda k: c[k] > 1, c))

find_all_duplicates([1, 2, 2, 3, 3, 3])  # [

[2, 3]

# 10 出现最多元素

In [21]:
def max_frequency(lst):
    return max(lst, default='列表为空', key=lambda v: lst.count(v))

lst = [1, 3, 3, 2, 1, 1, 2]
max_frequency(lst) # 1 

1

# 5 过滤掉各种空值

In [22]:
def filter_false(lst):
    return list(filter(bool, lst))

filter_false([None, 0, False, '', [], 'ok', [1, 2]])# ['ok', [1, 2]]

['ok', [1, 2]]

## 将list等分为子组

In [23]:
from math import ceil

def divide(lst, size):
    if size <= 0:
        return [lst]
    return [lst[i * size:(i+1)*size] for i in range(0, ceil(len(lst) / size))]

r = divide([1, 3, 5, 7, 9], 2) # [[1, 3], [5, 7], [9]]