In [2]:
import numpy as np

聚合

    np.average     加权平均值（arr1 , weights = arr2）
    np.mean        算术平均值（arr1）
    np.median      计算中位数
    np.sum         求和
    np.prod        求乘积（阶乘）
    np.cumprod     数组的累积乘积
    np.min         求最小
    np.max         求最大
 
    np.bincount    计算每个元素出现的次数



    np.argmin                沿指定维度查找最小值下标
    np.argmax                沿指定维度查找最大值下标
    np.nonzero               查找非零元素的下标
    np.where（condition）     根据条件查找或替换
    np.take(column,index)    #根据索引获取值
    np.argsort     沿着指定维度计算下标，按这个下标元素是递增的
    np.sort        沿指定维度 元素按递增顺序排序
    np.lexsort     根据多个array进行排序



    clip()函数计算：将所有比给定最大值num1还大的元素全部设为num1，
    而所有比给定最小值num2还小的元素全部设为给定的最小值num2
 
 
arr1. clip(num1,num2)  
arr1= [0 1 2 3 4]  
Clipped [1 1 2 2 2] 



# 单位矩阵

In [3]:
np.eye(3,3) 

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# 字符串堆矩阵 

In [4]:
A = np.eye(3,3)
B = A*3
np.bmat("A B;B A;A,B") ,np.bmat("A A B;B A A")

(matrix([[1., 0., 0., 3., 0., 0.],
         [0., 1., 0., 0., 3., 0.],
         [0., 0., 1., 0., 0., 3.],
         [3., 0., 0., 1., 0., 0.],
         [0., 3., 0., 0., 1., 0.],
         [0., 0., 3., 0., 0., 1.],
         [1., 0., 0., 3., 0., 0.],
         [0., 1., 0., 0., 3., 0.],
         [0., 0., 1., 0., 0., 3.]]),
 matrix([[1., 0., 0., 1., 0., 0., 3., 0., 0.],
         [0., 1., 0., 0., 1., 0., 0., 3., 0.],
         [0., 0., 1., 0., 0., 1., 0., 0., 3.],
         [3., 0., 0., 1., 0., 0., 1., 0., 0.],
         [0., 3., 0., 0., 1., 0., 0., 1., 0.],
         [0., 0., 3., 0., 0., 1., 0., 0., 1.]]))

## Allclose() 用于匹配两个数组并且以布尔值形式输出。如果两个数组的项在公差范围内不相等，则返回False。这是检查两个数组是否相似的好方法，

In [5]:
array1 = np.array([0.12,0.17,0.24,0.29])
array2 = np.array([0.13,0.19,0.26,0.31])# with a tolerance of 0.1, 

np.allclose(array1,array2,0.1)

False

In [6]:
np.allclose(array1,array2,0.2)

True

# argpartition() 找到N最大值索引。输出N最大值索引，然后根据需要，对值进行排序。

In [7]:
x = np.array([12, 10, 12, 0, 6, 8, 9, 1, 16, 4, 6,0])
index_val = np.argpartition(x, -4)[-4:]
index_val,np.sort(x[index_val])

(array([1, 8, 2, 0]), array([10, 12, 12, 16]))

# Clip() 用于将值保留在间隔的数组中。有时，需要将值保持在上限和下限之间。因此，可以使用NumPy的clip()函数。给定一个间隔，该间隔以外的值都将被裁剪到间隔边缘。

In [8]:
x = np.array([3, 17, 14, 23, 2, 2, 6, 8, 1, 2, 16,0])
np.clip(x,2,5)

array([3, 5, 5, 5, 2, 2, 5, 5, 2, 2, 5, 2])

# extract() 函数用于根据特定条件从数组中提取特定元素。有了该函数，还可以使用and和or等的语句。

In [9]:
array = np.random.randint(20, size=12)
cond = np.mod(array, 2)==1
array,cond

(array([18, 10,  4, 14,  2, 15, 17, 10, 14, 17,  4, 13]),
 array([False, False, False, False, False,  True,  True, False, False,
         True, False,  True]))

In [10]:
np.extract(cond, array)

array([15, 17, 17, 13])

In [11]:
np.extract(((array < 3) | (array > 15)), array)

array([18,  2, 17, 17])

# Percentile()用于计算沿指定轴的数组元素的第n个百分位数。

In [12]:
a = np.array([1,5,6,8,1,7,3,6,9])
print("50thPercentile of a, axis = 0 : ", np.percentile(a, 50, axis =0))
b =np.array([[10, 7, 4], [3, 2, 1]])
print("30th Percentile of b, axis = 0 :", np.percentile(b, 30, axis =0))

50thPercentile of a, axis = 0 :  6.0
30th Percentile of b, axis = 0 : [5.1 3.5 1.9]


# Where() 用于从满足特定条件的数组中返回元素。它返回在特定条件下值的索引位置。这差不多类似于在SQL中使用的where语句

In [13]:
y = np.array([1,5,6,8,1,7,3,6,9])
np.where(y>5),np.where(y>5, "Hit", "Miss")

((array([2, 3, 5, 7, 8]),),
 array(['Miss', 'Miss', 'Hit', 'Hit', 'Miss', 'Hit', 'Miss', 'Hit', 'Hit'],
       dtype='<U4'))

# np.random.shuffle() 随机打散序列

In [14]:
np.random.shuffle(y)
y

array([3, 6, 1, 6, 9, 1, 5, 7, 8])

# 找到两个矩阵相同元素的位置

In [15]:
a,b = (np.random.randn(10)*10).astype(int),(np.random.randn(10)*10).astype(int)
np.argwhere(a == b)

array([], shape=(0, 1), dtype=int64)

# 创建对角矩阵并设置对角数

In [16]:
A = np.diag([5,5,5,5,5])
A

array([[5, 0, 0, 0, 0],
       [0, 5, 0, 0, 0],
       [0, 0, 5, 0, 0],
       [0, 0, 0, 5, 0],
       [0, 0, 0, 0, 5]])

# 解上面矩阵的行列式

In [17]:
np.linalg.det(A)

3124.999999999999

# 求矩阵A的逆矩阵

In [18]:
B = np.linalg.inv(A)
B

array([[0.2, 0. , 0. , 0. , 0. ],
       [0. , 0.2, 0. , 0. , 0. ],
       [0. , 0. , 0.2, 0. , 0. ],
       [0. , 0. , 0. , 0.2, 0. ],
       [0. , 0. , 0. , 0. , 0.2]])

# 将矩阵 A，B 按列拼接

In [19]:
np.hstack((A,B))

array([[5. , 0. , 0. , 0. , 0. , 0.2, 0. , 0. , 0. , 0. ],
       [0. , 5. , 0. , 0. , 0. , 0. , 0.2, 0. , 0. , 0. ],
       [0. , 0. , 5. , 0. , 0. , 0. , 0. , 0.2, 0. , 0. ],
       [0. , 0. , 0. , 5. , 0. , 0. , 0. , 0. , 0.2, 0. ],
       [0. , 0. , 0. , 0. , 5. , 0. , 0. , 0. , 0. , 0.2]])

# 将矩阵 A,B 按行拼接

In [20]:
np.vstack((A,B))

array([[5. , 0. , 0. , 0. , 0. ],
       [0. , 5. , 0. , 0. , 0. ],
       [0. , 0. , 5. , 0. , 0. ],
       [0. , 0. , 0. , 5. , 0. ],
       [0. , 0. , 0. , 0. , 5. ],
       [0.2, 0. , 0. , 0. , 0. ],
       [0. , 0.2, 0. , 0. , 0. ],
       [0. , 0. , 0.2, 0. , 0. ],
       [0. , 0. , 0. , 0.2, 0. ],
       [0. , 0. , 0. , 0. , 0.2]])

# 用一个数包围原始矩阵周围（适合创建机器人边界条件，或者cnn的时候包围原始图像边界）

In [21]:
new = np.pad(A,pad_width = 1,constant_values=9)
new

array([[9, 9, 9, 9, 9, 9, 9],
       [9, 5, 0, 0, 0, 0, 9],
       [9, 0, 5, 0, 0, 0, 9],
       [9, 0, 0, 5, 0, 0, 9],
       [9, 0, 0, 0, 5, 0, 9],
       [9, 0, 0, 0, 0, 5, 9],
       [9, 9, 9, 9, 9, 9, 9]])

# 创建同值矩阵

In [22]:
np.full((2,2),7)

array([[7, 7],
       [7, 7]])

# 循环矩阵

In [26]:
a = np.r_[:7,:6]
a

array([0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5])

In [30]:
import scipy as sp
newa = sp.sparse.diags(a,np.r_[-6:7],shape=[7,7]).toarray()
newa

array([[6., 0., 1., 2., 3., 4., 5.],
       [5., 6., 0., 1., 2., 3., 4.],
       [4., 5., 6., 0., 1., 2., 3.],
       [3., 4., 5., 6., 0., 1., 2.],
       [2., 3., 4., 5., 6., 0., 1.],
       [1., 2., 3., 4., 5., 6., 0.],
       [0., 1., 2., 3., 4., 5., 6.]])

# 调换数组索引 np.transpose

In [34]:
a = np.r_[:4].reshape(2,2)
a

array([[0, 1],
       [2, 3]])

## 在二维展现就是转置

In [36]:
np.transpose(a),a.T

(array([[0, 2],
        [1, 3]]),
 array([[0, 2],
        [1, 3]]))

## 高维的展现就是定义转换维度

In [43]:
np.r_[:4,:4]

array([0, 1, 2, 3, 0, 1, 2, 3])

In [39]:
b = np.r_[:4,:4].reshape(2,2,2)
b

array([[[0, 1],
        [2, 3]],

       [[0, 1],
        [2, 3]]])

In [51]:
b.transpose(),b.transpose(1,0,2)

(array([[[0, 0],
         [2, 2]],
 
        [[1, 1],
         [3, 3]]]),
 array([[[0, 1],
         [0, 1]],
 
        [[2, 3],
         [2, 3]]]))

# 交换维度 np.swapaxes

In [65]:
b.swapaxes(1,0),b

(array([[[0, 1],
         [0, 1]],
 
        [[2, 3],
         [2, 3]]]),
 array([[[0, 1],
         [2, 3]],
 
        [[0, 1],
         [2, 3]]]))