# Python3内置函数汇总
https://www.zky.name/article/72.htmlhttps://www.zky.name/article/72.html

# Python 炫技操作：条件语句的七种写法
https://www.toutiao.com/a6810238705857462798/?tt_from=mobile_qq&utm_campaign=client_share&timestamp=1592257732&app=news_article_social&utm_source=mobile_qq&utm_medium=toutiao_ios&use_new_style=0&req_id=202006160548510100120351510E754E79&group_id=6810238705857462798

# Python pandas库159个常用方法使用说明
https://www.toutiao.com/a6816929966647673347/?tt_from=mobile_qq&utm_campaign=client_share&timestamp=1592257097&app=news_article_social&utm_source=mobile_qq&utm_medium=toutiao_ios&use_new_style=0&req_id=20200616053817010014040094367375A8&group_id=6816929966647673347

# 数据科学中100个Numpy代码技巧
https://www.toutiao.com/a6822918205942530571/?tt_from=mobile_qq&utm_campaign=client_share&timestamp=1592181860&app=news_article_social&utm_source=mobile_qq&utm_medium=toutiao_ios&use_new_style=0&req_id=202006150844190100140541411C05DBC7&group_id=6822918205942530571

# 有哪些开源的 Python 库让你相见恨晚？
1.https://www.toutiao.com/a6828877334800499203/?tt_from=mobile_qq&utm_campaign=client_share&timestamp=1592258093&app=news_article_social&utm_source=mobile_qq&utm_medium=toutiao_ios&use_new_style=0&req_id=202006160554530100140470760D651D5A&group_id=6828877334800499203
# Python库资源大全
2.https://zhuanlan.zhihu.com/p/27350980
# 数据集
3.https://github.com/awesomedata/awesome-public-datasets
# 中文数据集
4.https://blog.csdn.net/tmb8z9vdm66wh68vx1/article/details/93426915

## 清理变量

## 创建一个8x8矩阵，并用棋盘图案填充它（★☆☆）

In [1]:
import numpy as np
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## 考虑一个形状为（6,7,8）的数组，第100个元素的索引（x，y，z）是什么？（★☆☆）

In [2]:
print(np.unravel_index(99,(6,7,8)))

(1, 5, 3)


## 归一化一个5x5随机矩阵（★☆☆）

In [3]:
Z = np.random.random((5,5))
Z = (Z - np.mean (Z)) / (np.std (Z))
print(Z)

[[-0.87189924  0.63811708  0.54670269 -2.01195199 -0.93539718]
 [ 0.89855973 -1.96057586 -0.7009969   1.5459107   0.32923382]
 [-0.19763891 -1.39579345 -1.41498359  1.44554188  0.47445661]
 [ 1.07995893  0.98312467 -0.16614679 -0.16259597 -0.25180781]
 [-0.44485096  0.14101864  0.56622519  0.67169576  1.19409296]]


## 将5x3矩阵乘以3x2矩阵（实矩阵乘积）（★☆☆）

In [4]:
Z = np.dot(np.ones((5,3)), np.ones((3,2)))
print(Z)
# Alternative solution, in Python 3.5 and above
Z = np.ones((5,3)) @ np.ones((3,2))
print(Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]
[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [5]:
np.sqrt(-1) , np.emath.sqrt(-1)

/home/manman/anaconda3/envs/deepintorch/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


(nan, 1j)

## 何获取昨天，今天和明天的日期？

In [6]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
yesterday,today,tomorrow

(numpy.datetime64('2020-09-28'),
 numpy.datetime64('2020-09-29'),
 numpy.datetime64('2020-09-30'))

## 获取与2016年7月对应的所有日期？

In [7]:
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


## 一个生成器函数，该函数生成10个整数并使用它来重构数组

In [8]:
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


## 创建一个结构化网格，x和y坐标覆盖[0,1] x [0,1]区域

In [9]:
Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


## 找到向量中最接近给定标量的值？（★★☆）

In [10]:
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print(Z[index])

84


## 判断给定的2D数组是否有空列

In [11]:
Z = np.random.randint(0,3,(3,10))
print((~Z.any(axis=0)).any())
Z

True


array([[0, 0, 2, 2, 0, 0, 0, 1, 2, 1],
       [2, 1, 0, 0, 0, 1, 1, 0, 1, 1],
       [2, 1, 2, 2, 0, 2, 2, 0, 1, 1]])