In [35]:
import numpy as np
from scipy import stats as st

## 点积

In [36]:
a = np.array([[1,2],[3,4]]) 
b = np.array([[11,12],[13,14]]) 
a,b

(array([[1, 2],
        [3, 4]]),
 array([[11, 12],
        [13, 14]]))

In [37]:
np.vdot(a,b)

130

## 内积 $$ [[1*11+2*12, 1*13+2*14][3*11+4*12, 3*13+4*14]] $$

In [38]:
np.inner(a,b)

array([[35, 41],
       [81, 95]])

## 广播函数

In [39]:
import numpy.matlib 
import numpy as np 

In [40]:
a = [[1,0],[0,1]] 
b = [[4,1],[2,2]] 

In [41]:
np.matmul(a,b)

array([[4, 1],
       [2, 2]])

In [42]:
a1 = [[1,0],[1,2],[1,3],[1,4]]
b1 = [1,1] 

In [43]:
np.matmul(a1,b1)

array([1, 3, 4, 5])

## 高维广播函数

In [44]:
a2 = np.arange(8).reshape(2,2,2)
b2 = np.arange(4).reshape(2,2)
np.matmul(a2,b2),a2,b2

(array([[[ 2,  3],
         [ 6, 11]],
 
        [[10, 19],
         [14, 27]]]),
 array([[[0, 1],
         [2, 3]],
 
        [[4, 5],
         [6, 7]]]),
 array([[0, 1],
        [2, 3]]))

## numpy.linalg.det() 函数计算输入矩阵的行列式。

## 它从方阵的对角元素计算。 对于 2×2 矩阵，它是左上和右下元素的乘积与其他两个的乘积的差。
换句话说，对于矩阵[[a，b]，[c，d]]，行列式计算为 ad-bc。 较大的方阵被认为是 2×2 矩阵的组合。


In [45]:
a3 = np.array([[1,2], [3,4]])
print(a3)
np.linalg.det(a)

[[1 2]
 [3 4]]


1.0

[[ 6  1  1]
 [ 4 -2  5]
 [ 2  8  7]]
-306.0


## 从这儿就可以理解函数的计算过程了

In [46]:
print (6*(-2*7 - 5*8) - 1*(4*7 - 5*2) + 1*(4*8 - -2*2))
b = np.array([[6,1,1], [4, -2, 5], [2,8,7]]) 
print (b)
print (np.linalg.det(b))

-306
[[ 6  1  1]
 [ 4 -2  5]
 [ 2  8  7]]
-306.0


## 求逆

In [47]:
x = np.array([[1,2],[3,4]])
y = np.linalg.inv(x)
print (x)
print (y)
print (np.dot(x,y))

[[1 2]
 [3 4]]
[[-2.   1. ]
 [ 1.5 -0.5]]
[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]


## 解方程

In [48]:
import numpy as np 
 
a = np.array([[1,1,1],[0,2,5],[2,5,-1]]) 
 
print ('数组 a：')
print (a)
ainv = np.linalg.inv(a) 
 
print ('a 的逆：')
print (ainv)
 
print ('矩阵 b：')
b = np.array([[6],[-4],[27]]) 
print (b)
 
print ('计算：A^(-1)B：')
x = np.linalg.solve(a,b) 
print (x)
# 这就是线性方向 x = 5, y = 3, z = -2 的解

数组 a：
[[ 1  1  1]
 [ 0  2  5]
 [ 2  5 -1]]
a 的逆：
[[ 1.28571429 -0.28571429 -0.14285714]
 [-0.47619048  0.14285714  0.23809524]
 [ 0.19047619  0.14285714 -0.0952381 ]]
矩阵 b：
[[ 6]
 [-4]
 [27]]
计算：A^(-1)B：
[[ 5.]
 [ 3.]
 [-2.]]


In [49]:
x = np.dot(ainv,b)
x

array([[ 5.],
       [ 3.],
       [-2.]])