In [169]:
import numpy as np

## 一个单位矩阵

In [170]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

字符串堆矩阵 

In [171]:
A = np.eye(3,3)
B = A*3
np.bmat("A B;B A;A,B") ,np.bmat("A A B;B A A")

(matrix([[1., 0., 0., 3., 0., 0.],
         [0., 1., 0., 0., 3., 0.],
         [0., 0., 1., 0., 0., 3.],
         [3., 0., 0., 1., 0., 0.],
         [0., 3., 0., 0., 1., 0.],
         [0., 0., 3., 0., 0., 1.],
         [1., 0., 0., 3., 0., 0.],
         [0., 1., 0., 0., 3., 0.],
         [0., 0., 1., 0., 0., 3.]]),
 matrix([[1., 0., 0., 1., 0., 0., 3., 0., 0.],
         [0., 1., 0., 0., 1., 0., 0., 3., 0.],
         [0., 0., 1., 0., 0., 1., 0., 0., 3.],
         [3., 0., 0., 1., 0., 0., 1., 0., 0.],
         [0., 3., 0., 0., 1., 0., 0., 1., 0.],
         [0., 0., 3., 0., 0., 1., 0., 0., 1.]]))

# 线性代数计算

In [173]:
array , singular_matrix , vector , unit_vector , matrix  = np.arange(4) ,np.arange(16).reshape(4,4),np.arange(8).reshape(4,2),np.ones(4),np.random.rand(16).reshape(4,4)

In [174]:
{"数组":array , "奇异矩阵":singular_matrix ,"向量":vector ,"单位向量" :unit_vector,"矩阵":matrix}

{'数组': array([0, 1, 2, 3]),
 '奇异矩阵': array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]]),
 '向量': array([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7]]),
 '单位向量': array([1., 1., 1., 1.]),
 '矩阵': array([[0.9943217 , 0.71762737, 0.46451152, 0.74092439],
        [0.98493955, 0.76376358, 0.48794644, 0.87681174],
        [0.39382303, 0.8802659 , 0.21300662, 0.79369044],
        [0.56529173, 0.76148177, 0.72583675, 0.56106503]])}

### 数组点积 
    a = np.array([[1,2],[3,4]]), 
    b = np.array([[11,12],[13,14]]);
    np.dot(a,b)：
    [[1*11+2*13, 1*12+2*14],[3*11+4*13, 3*12+4*14]]

In [175]:
np.dot(np.array([[0, 1]
                ,[2, 3]
                ,[4, 5]]),np.array([[0, 1],[2, 3],[4, 5]]).T)

array([[ 1,  3,  5],
       [ 3, 13, 23],
       [ 5, 23, 41]])

In [176]:
unit_vector.dot(unit_vector)

4.0

In [177]:
array.dot(unit_vector)

6.0

### 两边对称乘，中间相同乘
    [[0, 1]         [[0, 1]
    ,[2, 3] =>T dot ,[2, 3]
    ,[4, 5]]        ,[4, 5]]
    [[0*0+2*2+4*4=20,1*0+3*2+5*4=26]
    ,[0*1+2*3+4*5=26,1*1+3*3+5*5=35]]
     [[0, 1]         [[0, 1]
    ,[2, 3] =>T dot ,[2, 3]
    ,[4, 5]]        ,[4, 5]]
    [[1*1+0*0,1*3+1*2,1*5+1*4,]
    ,[0*0+3*1,3*2+3*1,3*4]
    ,[5*0,5*2,5*4]


In [178]:
np.array([[0, 1]
         ,[2, 3]
         ,[4, 5]]).T.dot(np.array([[0, 1],[2, 3],[4, 5]]))

array([[20, 26],
       [26, 35]])

In [179]:
np.array([[0*0+2*2+4*4,1*0+3*2+5*4],[0*1+2*3+4*5,1*1+3*3+5*5]])

array([[20, 26],
       [26, 35]])

### 一个单位矩阵

In [180]:
np.array([[1,0],[0,1]]).T.dot(np.array([[1,0],[0,1]]))

array([[1, 0],
       [0, 1]])

### 向量点积
    a = np.array([[1,2],[3,4]]) ,
    b = np.array([[11,12],[13,14]]) ;
    np.vdot(a,b)：1*11 + 2*12 + 3*13 + 4*14 = 130

In [181]:
np.vdot(vector,vector)

140

### 数组内积/*乘

In [182]:
np.inner(array,array)

14

In [183]:
np.inner(unit_vector,unit_vector)

4.0

In [184]:
np.matmul(vector.T,vector)

array([[56, 68],
       [68, 84]])

### 矩阵积/矩阵乘法

In [216]:
singular_matrix.dot(matrix)

array([[ 3.46846082,  4.80874071,  3.09146994,  4.1473877 ],
       [15.22196489, 17.30129525, 10.65667529, 16.03735408],
       [26.97546896, 29.79384979, 18.22188064, 27.92732046],
       [38.72897303, 42.28640433, 25.78708599, 39.81728684]])

### 奇异值分解

In [219]:
U,Sigma,V = np.linalg.svd(singular_matrix,full_matrices=False)
{"U = ":U,"Sigma = ":Sigma,"V = ":V}

{'U = ': array([[-0.09184212, -0.83160389,  0.53389888,  0.12227833],
        [-0.31812733, -0.44586433, -0.80300606,  0.23490695],
        [-0.54441254, -0.06012478,  0.00431548, -0.8366489 ],
        [-0.77069775,  0.32561478,  0.2647917 ,  0.47946362]]),
 'Sigma = ': array([3.51399637e+01, 2.27661021e+00, 1.79164689e-15, 9.84875082e-17]),
 'V = ': array([[-0.42334086, -0.47243254, -0.52152422, -0.57061589],
        [ 0.72165263,  0.27714165, -0.16736932, -0.6118803 ],
        [-0.27207983,  0.71708979, -0.6179401 ,  0.17293014],
        [ 0.47536572, -0.43102463, -0.5640479 ,  0.51970681]])}

In [211]:
print('----------------SVD奇异值分解---------------')
Arr2 = np.mat("4 11 14;8 7 -2")
U,Sigma,V = np.linalg.svd(Arr2,full_matrices=False)
print("U =",U)
print("sigma =",Sigma)
print("V =",V)

----------------SVD奇异值分解---------------
U = [[-0.9486833  -0.31622777]
 [-0.31622777  0.9486833 ]]
sigma = [18.97366596  9.48683298]
V = [[-0.33333333 -0.66666667 -0.66666667]
 [ 0.66666667  0.33333333 -0.66666667]]


### 行列式
### 求解线性方程

In [206]:
"矩阵行列式的计算(非奇异矩阵行列式不为0)：",np.linalg.det(matrix)

('矩阵行列式的计算(非奇异矩阵行列式不为0)：', 0.028289969500549295)

In [207]:
"矩阵行列式的计算奇(异矩阵的行列式为0)：",np.linalg.det(singular_matrix)

('矩阵行列式的计算奇(异矩阵的行列式为0)：', 0.0)

In [208]:
"一个典型的奇异矩阵行列式:",np.linalg.det([[1,0],[1,0]])

('一个典型的奇异矩阵行列式:', 0.0)

### 求逆

In [189]:
np.linalg.inv(matrix)

array([[ 4.35483478, -2.7180004 , -0.48476915, -0.8175024 ],
       [ 6.84109294, -7.97581383,  2.18211922,  0.34332459],
       [-3.82743237,  3.28571415, -1.51516337,  2.06296217],
       [-8.72096521,  9.31266013, -0.51303637, -0.52878332]])

### 求伪逆运 

In [190]:
np.linalg.pinv(singular_matrix)

array([[-2.62500000e-01, -1.37500000e-01, -1.25000000e-02,
         1.12500000e-01],
       [-1.00000000e-01, -5.00000000e-02,  2.06320288e-17,
         5.00000000e-02],
       [ 6.25000000e-02,  3.75000000e-02,  1.25000000e-02,
        -1.25000000e-02],
       [ 2.25000000e-01,  1.25000000e-01,  2.50000000e-02,
        -7.50000000e-02]])

### 求单位矩阵
非奇异矩阵求单位矩阵

In [192]:
matrix.dot(np.linalg.inv(matrix))

array([[ 1.00000000e+00, -8.45428470e-17, -7.32483049e-17,
        -6.25407607e-18],
       [ 4.17364683e-16,  1.00000000e+00, -1.98926355e-16,
        -1.10911732e-16],
       [-3.47037881e-16,  5.62640505e-16,  1.00000000e+00,
         1.65573460e-18],
       [-2.02711622e-16,  5.37886396e-16,  1.24515051e-16,
         1.00000000e+00]])

奇异矩阵用伪逆求单位矩阵

In [191]:
singular_matrix.dot(np.linalg.pinv(singular_matrix))

array([[ 0.7,  0.4,  0.1, -0.2],
       [ 0.4,  0.3,  0.2,  0.1],
       [ 0.1,  0.2,  0.3,  0.4],
       [-0.2,  0.1,  0.4,  0.7]])

In [215]:
print('------------逆矩阵与单位矩阵---------------')  
import numpy as np  
A = np.mat("0 1 2;1 0 3;4 -3 8")  
print("A=",A)  
inverse = np.linalg.inv(A)  
print(u"A的逆矩阵：","\n",inverse)  
I = A*inverse  
print('单位矩阵:I = A*inverse：',"\n",I)  

------------逆矩阵与单位矩阵---------------
A= [[ 0  1  2]
 [ 1  0  3]
 [ 4 -3  8]]
A的逆矩阵： 
 [[-4.5  7.  -1.5]
 [-2.   4.  -1. ]
 [ 1.5 -2.   0.5]]
单位矩阵:I = A*inverse： 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [214]:
print('------------逆矩阵与单位矩阵---------------')  
import numpy as np  
A = np.mat("0 1 2;1 0 3;4 -3 8")  
print("矩阵A =",A)  
inverse = np.linalg.inv(A)  
print(u"A的逆矩阵：","\n",inverse)  
I = A*inverse  
print('单位矩阵:I = A*inverse：',"\n",I)  

------------逆矩阵与单位矩阵---------------
矩阵A = [[ 0  1  2]
 [ 1  0  3]
 [ 4 -3  8]]
A的逆矩阵： 
 [[-4.5  7.  -1.5]
 [-2.   4.  -1. ]
 [ 1.5 -2.   0.5]]
单位矩阵:I = A*inverse： 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
