In [1]:
import numpy as np

In [2]:
"w∑ qœ e´ r® t† y¥ u¨ iˆ oø pπ [“ ]‘ \« aå sß d∂ fƒ g© h˙ j∆ k˚ l¬ ;… 'æ "

"w∑ qœ e´ r® t† y¥ u¨ iˆ oø pπ [“ ]‘ \\« aå sß d∂ fƒ g© h˙ j∆ k˚ l¬ ;… 'æ "

## 状态概率转化图可以以矩阵的形式表示。如果我们定义矩阵阵P某一位置P(i, j)的值为P(j|i)，即从状态i变为状态j的概率
## 得到条件如下:
## init_array : 是初始概率 分别为 0.1 ,0.2 ,0.7
## 转移矩阵 transfer_matrix : 第一行是0.1的转移概率,第二行是0.2的转移概率,第三行是0.7的转移概率	
 

In [3]:
def transitionprobability(A):
    left , right = [],[]
    initA = np.array(A)
    An = initA.shape[0]
    unitVector = np.ones(An)
    distionA = np.array([j for j in {i:0 for i in A}.keys()])
    probability = lambda  elements , n : {e:(elements==e).dot(np.ones(n))/n for e in elements}
    prob_list = lambda prob_dict:[prob_dict[i] for i in prob_dict]

    transfer_matrix_left , transfer_matrix_right,nameList_left,nameList_right = [],[],[],[]
    for e in distionA:
        one_E_index = np.where(initA==e)[0]
        bool_left = one_E_index[one_E_index -1 >= 0]
        bool_right = one_E_index[one_E_index + 1 < An]
        left = bool_left - 1
        right = bool_right + 1
        if len(left) > 0:
            nameList_left.append(e)
            init_dict_left = {i : 0 for i in initA}
            left_elements = initA[left]
            ln = left_elements.shape[0]
            prob_left = probability(left_elements,ln)
            init_dict_left.update(prob_left)
            transfer_matrix_left.append(prob_list(init_dict_left))
            print('left',e,transfer_matrix_left[-1],init_dict_left)
        if len(right) > 0:
            nameList_right.append(e)
            init_dict_right = {i : 0 for i in initA}
            right_elements = initA[right]
            rn = right_elements.shape[0]
            prob_right = probability(right_elements,rn)
            init_dict_right.update(prob_right)
            transfer_matrix_right.append(prob_list(init_dict_right))
            print('right',e,transfer_matrix_right[-1],init_dict_right)
         
    return {'cloumn_names_left':init_dict_left.keys()
    ,'transfer_matrix_left':np.array(transfer_matrix_left)
    ,'cloumn_names_right':init_dict_right.keys()
    ,'transfer_matrix_right':np.array(transfer_matrix_right)}

In [4]:
init_array = np.array([0.1, 0.2, 0.7])
transfer_matrix = np.array([[0.9, 0.075, 0.025],
                            [0.15, 0.8, 0.05],
                            [0.25, 0.25, 0.5]])

## numpy 的一个小发现，np.dot(矩阵.T,向量) == np.dot(向量,矩阵)

In [5]:
np.dot(init_array,transfer_matrix)==np.dot(transfer_matrix.T,init_array)

array([ True,  True,  True])

In [6]:
def markov(init_array,transfer_matrix,maxloop=100):
    #转移矩阵
    results = []
    restmp = init_array #迭代结果
    for i in range(maxloop):
        res = np.dot(transfer_matrix.T,restmp)
        results.append(res)
        restmp = res
    return np.array(results)



markov(init_array,transfer_matrix,100)

array([[0.295     , 0.3425    , 0.3625    ],
       [0.4075    , 0.38675   , 0.20575   ],
       [0.4762    , 0.3914    , 0.1324    ],
       [0.52039   , 0.381935  , 0.097675  ],
       [0.55006   , 0.368996  , 0.080944  ],
       [0.5706394 , 0.3566873 , 0.0726733 ],
       [0.58524688, 0.34631612, 0.068437  ],
       [0.59577886, 0.33805566, 0.06616548],
       [0.60345069, 0.33166931, 0.06487999],
       [0.60907602, 0.32681425, 0.06410973],
       [0.61321799, 0.32315953, 0.06362248],
       [0.61627574, 0.3204246 , 0.06329967],
       [0.61853677, 0.31838527, 0.06307796],
       [0.62021037, 0.31686797, 0.06292166],
       [0.62144995, 0.31574057, 0.06280949],
       [0.62236841, 0.31490357, 0.06272802],
       [0.62304911, 0.31428249, 0.0626684 ],
       [0.62355367, 0.31382178, 0.06262455],
       [0.62392771, 0.31348008, 0.06259221],
       [0.624205  , 0.3132267 , 0.0625683 ],
       [0.62441058, 0.31303881, 0.06255061],
       [0.624563  , 0.31289949, 0.06253751],
       [0.

In [7]:
info  = ['胜','负','平','胜','平','负',
'平','胜']

In [8]:
test = transitionprobability(info)

left 胜 [0, 0, 1.0] {'胜': 0, '负': 0, '平': 1.0}
right 胜 [0, 0.5, 0.5] {'胜': 0, '负': 0.5, '平': 0.5}
left 负 [0.5, 0, 0.5] {'胜': 0.5, '负': 0, '平': 0.5}
right 负 [0, 0, 1.0] {'胜': 0, '负': 0, '平': 1.0}
left 平 [0.3333333333333333, 0.6666666666666666, 0] {'胜': 0.3333333333333333, '负': 0.6666666666666666, '平': 0}
right 平 [0.6666666666666666, 0.3333333333333333, 0] {'胜': 0.6666666666666666, '负': 0.3333333333333333, '平': 0}


In [9]:
test

{'cloumn_names_left': dict_keys(['胜', '负', '平']),
 'transfer_matrix_left': array([[0.        , 0.        , 1.        ],
        [0.5       , 0.        , 0.5       ],
        [0.33333333, 0.66666667, 0.        ]]),
 'cloumn_names_right': dict_keys(['胜', '负', '平']),
 'transfer_matrix_right': array([[0.        , 0.5       , 0.5       ],
        [0.        , 0.        , 1.        ],
        [0.66666667, 0.33333333, 0.        ]])}

In [10]:
test['transfer_matrix_left']

array([[0.        , 0.        , 1.        ],
       [0.5       , 0.        , 0.5       ],
       [0.33333333, 0.66666667, 0.        ]])

In [11]:
markov(transfer_matrix=test['transfer_matrix_right'],init_array=np.ones(len(set(info))))

array([[0.66666667, 0.83333333, 1.5       ],
       [1.        , 0.83333333, 1.16666667],
       [0.77777778, 0.88888889, 1.33333333],
       [0.88888889, 0.83333333, 1.27777778],
       [0.85185185, 0.87037037, 1.27777778],
       [0.85185185, 0.85185185, 1.2962963 ],
       [0.86419753, 0.85802469, 1.27777778],
       [0.85185185, 0.85802469, 1.29012346],
       [0.8600823 , 0.85596708, 1.28395062],
       [0.85596708, 0.85802469, 1.28600823],
       [0.85733882, 0.85665295, 1.28600823],
       [0.85733882, 0.85733882, 1.28532236],
       [0.85688157, 0.8571102 , 1.28600823],
       [0.85733882, 0.8571102 , 1.28555098],
       [0.85703399, 0.8571864 , 1.28577961],
       [0.8571864 , 0.8571102 , 1.2857034 ],
       [0.8571356 , 0.857161  , 1.2857034 ],
       [0.8571356 , 0.8571356 , 1.2857288 ],
       [0.85715253, 0.85714407, 1.2857034 ],
       [0.8571356 , 0.85714407, 1.28572033],
       [0.85714689, 0.85714124, 1.28571187],
       [0.85714124, 0.85714407, 1.28571469],
       [0.