In [1]:
import torch
import numpy as np

## 定义数据集

In [2]:
z = np.random.randint(0,10,10)
x = torch.FloatTensor(z)
x

tensor([1., 8., 3., 5., 0., 1., 7., 0., 3., 4.])

## 封装为类准备

In [3]:
class torch_stats:
    def __init__(self):
        pass
    
    def _type(self,*data):
        return [torch.Tensor(i) for i in data]
ts = torch_stats()
ts._type(z,z)

[tensor([1., 8., 3., 5., 0., 1., 7., 0., 3., 4.]),
 tensor([1., 8., 3., 5., 0., 1., 7., 0., 3., 4.])]

## 余弦相似度

In [4]:
def cosangle(vector1,vector2)->torch.Tensor:
    cosl = vector1.dot(vector2)/(torch.norm(vector1)*torch.norm(vector2))
    pi = torch.FloatTensor([np.pi])
    cos = cosl*2*pi
    radian = cosl*(pi/180)
    return {'cosangle':cosl,'cos':cos,'radian':radian}
cosangle(x,x)

{'cosangle': tensor(1.0000),
 'cos': tensor([6.2832]),
 'radian': tensor([0.0175])}

## 信息熵

In [5]:
def infoEntropy(X,x,In='bit')->torch.Tensor:
    n = torch.Tensor([X.shape[0]])
    px = torch.sum(X==x)/n
    if In == 'bit':
        return -px*torch.log2(px)
    elif In == 'nat':
        return -px*torch.log(px)
infoEntropy(x,x[1],'nat')

tensor([0.2303])

## 总体信息熵

In [6]:
def infoEntropys(X,In='bit')->torch.Tensor:
    entropy_i = torch.Tensor([infoEntropy(X,x)[0] for x in X])
    return {'entropy':np.unique(entropy_i).sum(),'probability':{x:p for x,p in zip(X.numpy(),entropy_i)}}
infoEntropys(x)

{'entropy': 0.7965784,
 'probability': {1.0: tensor(0.4644),
  8.0: tensor(0.3322),
  3.0: tensor(0.4644),
  5.0: tensor(0.3322),
  0.0: tensor(0.4644),
  7.0: tensor(0.3322),
  4.0: tensor(0.3322)}}