### 将一个十进制数除以二，得到的商再除以二，以此类推，直到商等于一或零时为止，然后依照倒序取除得的余数，即换算为二进制数的结果。比如32除以2，商是16，余数是0，然后再用商16除以2，得到余数0，以此类推，得到6个余数，再倒序排列，就是100000。要点是：除二取余，倒序排列。    
### 我们将这些药从0～63按照二进制编号，获得64个六位数的二进制编号，也就是从000000（六个零）到111111（六个一），每个二进制编号的最左边是第一位，最右边是第六位。
### 然后选六只老鼠从左到右排开，和二进制的六位，从左到右地依次对应。文稿里的二进制编号，你可以试着一位一位竖着看，下面每只老鼠负责一位。
### 从左边数第一个老鼠吃对应的二进制是1的药，0就不吃。那么老鼠1依次吃第32，33，34，……，63号药。第二只吃16，17，……，31，48，49，……，63号药，等等。最后一只老鼠吃1，3，5，……，63号药。你可能注意到了，6只老鼠都吃了63号，那是因为63对应的二进制编号是6个1，所以6只都要吃。
### 吃完药之后三天，某些老鼠可能死了，我们假定第1，2，6这三只老鼠死了，剩下的活着。这说明什么呢？说明编号110001号药有问题，也就是在第1，第2，第6位上分别是3个1，因为这三只老鼠都吃了它，而3，4，5这三只没死的老鼠没有吃它（对应的位置为0）。而110001对应十进制的49，也就是说第49瓶药是毒药。将一个十进制数除以二，得到的商再除以二，以此类推，直到商等于一或零时为止，然后依照倒序取除得的余数，即换算为二进制数的结果。比如32除以2，商是16，余数是0，然后再用商16除以2，得到余数0，以此类推，得到6个余数，再倒序排列，就是100000。要点是：除二取余，倒序排列。    
### 我们将这些药从0～63按照二进制编号，获得64个六位数的二进制编号，也就是从000000（六个零）到111111（六个一），每个二进制编号的最左边是第一位，最右边是第六位。
### 然后选六只老鼠从左到右排开，和二进制的六位，从左到右地依次对应。文稿里的二进制编号，你可以试着一位一位竖着看，下面每只老鼠负责一位。
### 从左边数第一个老鼠吃对应的二进制是1的药，0就不吃。那么老鼠1依次吃第32，33，34，……，63号药。第二只吃16，17，……，31，48，49，……，63号药，等等。最后一只老鼠吃1，3，5，……，63号药。你可能注意到了，6只老鼠都吃了63号，那是因为63对应的二进制编号是6个1，所以6只都要吃。
### 吃完药之后三天，某些老鼠可能死了，我们假定第1，2，6这三只老鼠死了，剩下的活着。这说明什么呢？说明编号110001号药有问题，也就是在第1，第2，第6位上分别是3个1，因为这三只老鼠都吃了它，而3，4，5这三只没死的老鼠没有吃它（对应的位置为0）。而110001对应十进制的49，也就是说第49瓶药是毒药。

In [1]:
import math
import numpy as np

# 二进制编码机

In [2]:
def binarycoder(quotient):
    result = []
    while quotient > 0:  
        quotient,remainder=divmod(quotient,2)
        result.append(remainder)
    return result[::-1]

# 二进制编码范围

In [3]:
def binary_range(n):
    max_index = n - 1
    max_lenght = len(binarycoder(max_index))
    return [[0]*(max_lenght - len(binarycoder(i)))+binarycoder(i) for i in range(n)]
binary_range(64)

[[0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 1],
 [0, 0, 0, 0, 1, 0],
 [0, 0, 0, 0, 1, 1],
 [0, 0, 0, 1, 0, 0],
 [0, 0, 0, 1, 0, 1],
 [0, 0, 0, 1, 1, 0],
 [0, 0, 0, 1, 1, 1],
 [0, 0, 1, 0, 0, 0],
 [0, 0, 1, 0, 0, 1],
 [0, 0, 1, 0, 1, 0],
 [0, 0, 1, 0, 1, 1],
 [0, 0, 1, 1, 0, 0],
 [0, 0, 1, 1, 0, 1],
 [0, 0, 1, 1, 1, 0],
 [0, 0, 1, 1, 1, 1],
 [0, 1, 0, 0, 0, 0],
 [0, 1, 0, 0, 0, 1],
 [0, 1, 0, 0, 1, 0],
 [0, 1, 0, 0, 1, 1],
 [0, 1, 0, 1, 0, 0],
 [0, 1, 0, 1, 0, 1],
 [0, 1, 0, 1, 1, 0],
 [0, 1, 0, 1, 1, 1],
 [0, 1, 1, 0, 0, 0],
 [0, 1, 1, 0, 0, 1],
 [0, 1, 1, 0, 1, 0],
 [0, 1, 1, 0, 1, 1],
 [0, 1, 1, 1, 0, 0],
 [0, 1, 1, 1, 0, 1],
 [0, 1, 1, 1, 1, 0],
 [0, 1, 1, 1, 1, 1],
 [1, 0, 0, 0, 0, 0],
 [1, 0, 0, 0, 0, 1],
 [1, 0, 0, 0, 1, 0],
 [1, 0, 0, 0, 1, 1],
 [1, 0, 0, 1, 0, 0],
 [1, 0, 0, 1, 0, 1],
 [1, 0, 0, 1, 1, 0],
 [1, 0, 0, 1, 1, 1],
 [1, 0, 1, 0, 0, 0],
 [1, 0, 1, 0, 0, 1],
 [1, 0, 1, 0, 1, 0],
 [1, 0, 1, 0, 1, 1],
 [1, 0, 1, 1, 0, 0],
 [1, 0, 1, 1, 0, 1],
 [1, 0, 1, 1, 1, 0],
 [1, 0, 1, 1,

# 需要的测试单元数量

In [4]:
import os 
def AB_test_Unit(n):
    math = __import__("math")
    return math.ceil(math.log(n,2))
AB_test_Unit(65)

7

# 测试单元顺序下标

In [5]:
def ABtestsorted(elements):
    result = []
    unit = int(AB_test_Unit(len(elements)))
    binarycodes = np.array(binary_range(len(elements)))
    for i in range(unit):
        index_ = binarycodes[:,i]
        result.append(np.ravel(np.argwhere(index_ != 0)))
    return np.array(result)



In [6]:
ABtestsorted(list(range(64)))

array([[32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
        48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63],
       [16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63],
       [ 8,  9, 10, 11, 12, 13, 14, 15, 24, 25, 26, 27, 28, 29, 30, 31,
        40, 41, 42, 43, 44, 45, 46, 47, 56, 57, 58, 59, 60, 61, 62, 63],
       [ 4,  5,  6,  7, 12, 13, 14, 15, 20, 21, 22, 23, 28, 29, 30, 31,
        36, 37, 38, 39, 44, 45, 46, 47, 52, 53, 54, 55, 60, 61, 62, 63],
       [ 2,  3,  6,  7, 10, 11, 14, 15, 18, 19, 22, 23, 26, 27, 30, 31,
        34, 35, 38, 39, 42, 43, 46, 47, 50, 51, 54, 55, 58, 59, 62, 63],
       [ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31,
        33, 35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63]])

## 整理代码

In [7]:
import numpy as np

def binarycoder(quotient):
    result = []
    while quotient > 0:  
        quotient,remainder=divmod(quotient,2)
        result.append(remainder)
    return result[::-1]

def binary_range(n):
    max_index = n - 1
    max_lenght = len(binarycoder(max_index))
    return [[0]*(max_lenght - len(binarycoder(i)))+binarycoder(i) for i in range(n)]

def AB_test_Unit(n):
    math = __import__("math")
    return math.ceil(math.log2(n))

def ABtest_sequence(elements):
    result = []
    m = len(elements)
    unit = int(AB_test_Unit(m))
    binarycodes = np.array(binary_range(m))
    for i in range(unit):
        index_ = binarycodes[:,i]
        result.append(np.ravel(np.argwhere(index_ != 0)))
    return {"测试序号":np.array(result),"需要测试单位数量":unit,"二进制编码":binarycodes}

In [8]:
ABtest_sequence(list(range(66)))

{'测试序号': array([array([64, 65]),
        array([32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63]),
        array([16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63]),
        array([ 8,  9, 10, 11, 12, 13, 14, 15, 24, 25, 26, 27, 28, 29, 30, 31, 40,
        41, 42, 43, 44, 45, 46, 47, 56, 57, 58, 59, 60, 61, 62, 63]),
        array([ 4,  5,  6,  7, 12, 13, 14, 15, 20, 21, 22, 23, 28, 29, 30, 31, 36,
        37, 38, 39, 44, 45, 46, 47, 52, 53, 54, 55, 60, 61, 62, 63]),
        array([ 2,  3,  6,  7, 10, 11, 14, 15, 18, 19, 22, 23, 26, 27, 30, 31, 34,
        35, 38, 39, 42, 43, 46, 47, 50, 51, 54, 55, 58, 59, 62, 63]),
        array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
        35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65])],
       dtype=object),
 '需要测试单位数量': 7,
 '二进制编