In [2]:
import numpy as np
import random

In [3]:
example = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
a,b = set(random.sample(example, 5)),set(random.sample(example, 5))
a,b

({2, 3, 4, 5, 7}, {1, 2, 3, 4, 10})

In [4]:
arra , arrb = np.array(list(a)) ,np.array(list(b))
arra , arrb

(array([2, 3, 4, 5, 7]), array([ 1,  2,  3,  4, 10]))

## 交集

In [5]:
a&b

{2, 3, 4}

In [6]:
a.intersection(b)

{2, 3, 4}

In [7]:
np.intersect1d(arra,arrb)

array([2, 3, 4])

## 并集

In [8]:
a|b

{1, 2, 3, 4, 5, 7, 10}

In [9]:
a.union(b)

{1, 2, 3, 4, 5, 7, 10}

In [10]:
np.union1d(arra,arrb)

array([ 1,  2,  3,  4,  5,  7, 10])

## 差集

In [11]:
a-b

{5, 7}

In [12]:
a.difference(b)

{5, 7}

In [13]:
np.setdiff1d(arra,arrb)

array([5, 7])

In [14]:
b-a

{1, 10}

In [15]:
b.difference(a)

{1, 10}

In [16]:
np.setdiff1d(arrb,arra)

array([ 1, 10])

## 对称差集(返回两个集合中不重复的元素集合。)

In [17]:
a^b

{1, 5, 7, 10}

In [18]:
a.symmetric_difference(b)

{1, 5, 7, 10}

In [19]:
np.setxor1d(arrb,arra)

array([ 1,  5,  7, 10])

## 判断是否父集（包含）

In [20]:
(b-a).issubset(b)

True

In [21]:
(b-a)|(b)==b

True

In [22]:
arrb[arra-arrb] in arrb

True

## 判断是否子集

In [23]:
b.issuperset(b-a)

True

In [24]:
b&(b-a)==b-a

True

In [25]:
arrb[arra-arrb] in arra

True

## 判断两个集合是否包含相同的元

In [26]:
(len(a-b)>0) | (len(b-a)>0)

True

In [27]:
a.isdisjoint(b)

False

## 移除当前集合中在另外一个指定集合相同的元素，并将另外一个指定集合中不同的元素插入到当前集合中。

In [28]:
a.symmetric_difference_update(b)
a

{1, 5, 7, 10}