In [7]:
import numpy as np

In [8]:
dataset = [['牛奶','洋葱','肉豆蔻','芸豆','鸡蛋','酸奶'],
        ['莳萝','洋葱','肉豆蔻','芸豆','鸡蛋','酸奶'],
        ['牛奶','苹果','芸豆','鸡蛋'],
        ['牛奶','独角兽','玉米','芸豆','酸奶'],
        ['玉米','洋葱','洋葱','芸豆','冰淇淋','鸡蛋']]

In [9]:
def one_hot_func(dataset):
    lenghts = np.array([len(row) for row in dataset])
    max_lenght = lenghts.max()
    m = len(lenghts)
    zero_mat= np.zeros((max_lenght,m))
    init_mat = np.array([dataset[i]+[0]*(max_lenght-lenghts[i]) for i in range(m)])
    distinct = np.unique(init_mat)
    del_0_in_distinct = distinct[distinct != '0']
    one_hot_dict , counts = dict(),np.zeros(del_0_in_distinct.size)
    n = -1
    for element in del_0_in_distinct :
        n += 1
        bool_mat = init_mat==element
        one_hot_dict.update({element:bool_mat})
        counts[n] = bool_mat.sum()
    return counts,one_hot_dict
    
one_hot_func(dataset)

(array([1., 4., 3., 1., 2., 2., 5., 1., 1., 3., 4.]),
 {'冰淇淋': array([[False, False, False, False, False, False],
         [False, False, False, False, False, False],
         [False, False, False, False, False, False],
         [False, False, False, False, False, False],
         [False, False, False, False,  True, False]]),
  '洋葱': array([[False,  True, False, False, False, False],
         [False,  True, False, False, False, False],
         [False, False, False, False, False, False],
         [False, False, False, False, False, False],
         [False,  True,  True, False, False, False]]),
  '牛奶': array([[ True, False, False, False, False, False],
         [False, False, False, False, False, False],
         [ True, False, False, False, False, False],
         [ True, False, False, False, False, False],
         [False, False, False, False, False, False]]),
  '独角兽': array([[False, False, False, False, False, False],
         [False, False, False, False, False, False],
         [Fal

In [10]:
np.percentile(np.ones(10),0.5)

1.0

In [11]:
def fathom(counts=None,one_hot_dict=None,per = 0.5,need_keys=None,need_bool_mat=None,need_counts=None):
    try:
        percentile = np.percentile(counts, per*100)
        need_keys , need_bool_mat ,need_counts = [],[],[]
        for (key,value),count in zip(one_hot_dict.items(),counts):
            if count >= percentile:
                need_keys.append(key)
                need_bool_mat.append(value)
                need_counts.append(count)   
        return need_keys,need_bool_mat,need_counts
    except Exception as error:
        return False
fathom(dataset)

False

In [12]:
a,b = np.array([[False, False, False, False, False, False],
          [False, False, False, False, False, False],
          [False, False, False, False, False, False],
          [False, False,  True, False, False, False],
          [ True, False, False, False, False, False]]),np.array([[False, False,  True, False, False, False],
          [False, False,  True, False, False, False],
          [False, False, False, False, False, False],
          [False, False, False, False, False, False],
          [False, False, False, False, False, False]])
a+b

array([[False, False,  True, False, False, False],
       [False, False,  True, False, False, False],
       [False, False, False, False, False, False],
       [False, False,  True, False, False, False],
       [ True, False, False, False, False, False]])

In [13]:
def Apriori(dataset,per = 0.5,need_keys=None,need_bool_mat=None,need_counts=None):
    counts,one_hot_dict = one_hot_func(dataset)
    names = list(one_hot_dict)
    percentile = np.percentile(counts, per*100)
    sorted_counts = sorted(counts)[::-1]
    for end in range(len(sorted_counts)):
        for start in range(end):
            print(names[start:end])
        #need_keys,need_bool_mat,need_counts = fathom(counts,one_hot_dict,per)
    return start,sorted_counts
Apriori(dataset,per=0.5)

['冰淇淋']
['冰淇淋', '洋葱']
['洋葱']
['冰淇淋', '洋葱', '牛奶']
['洋葱', '牛奶']
['牛奶']
['冰淇淋', '洋葱', '牛奶', '独角兽']
['洋葱', '牛奶', '独角兽']
['牛奶', '独角兽']
['独角兽']
['冰淇淋', '洋葱', '牛奶', '独角兽', '玉米']
['洋葱', '牛奶', '独角兽', '玉米']
['牛奶', '独角兽', '玉米']
['独角兽', '玉米']
['玉米']
['冰淇淋', '洋葱', '牛奶', '独角兽', '玉米', '肉豆蔻']
['洋葱', '牛奶', '独角兽', '玉米', '肉豆蔻']
['牛奶', '独角兽', '玉米', '肉豆蔻']
['独角兽', '玉米', '肉豆蔻']
['玉米', '肉豆蔻']
['肉豆蔻']
['冰淇淋', '洋葱', '牛奶', '独角兽', '玉米', '肉豆蔻', '芸豆']
['洋葱', '牛奶', '独角兽', '玉米', '肉豆蔻', '芸豆']
['牛奶', '独角兽', '玉米', '肉豆蔻', '芸豆']
['独角兽', '玉米', '肉豆蔻', '芸豆']
['玉米', '肉豆蔻', '芸豆']
['肉豆蔻', '芸豆']
['芸豆']
['冰淇淋', '洋葱', '牛奶', '独角兽', '玉米', '肉豆蔻', '芸豆', '苹果']
['洋葱', '牛奶', '独角兽', '玉米', '肉豆蔻', '芸豆', '苹果']
['牛奶', '独角兽', '玉米', '肉豆蔻', '芸豆', '苹果']
['独角兽', '玉米', '肉豆蔻', '芸豆', '苹果']
['玉米', '肉豆蔻', '芸豆', '苹果']
['肉豆蔻', '芸豆', '苹果']
['芸豆', '苹果']
['苹果']
['冰淇淋', '洋葱', '牛奶', '独角兽', '玉米', '肉豆蔻', '芸豆', '苹果', '莳萝']
['洋葱', '牛奶', '独角兽', '玉米', '肉豆蔻', '芸豆', '苹果', '莳萝']
['牛奶', '独角兽', '玉米', '肉豆蔻', '芸豆', '苹果', '莳萝']
['独角兽', '玉米', '肉豆蔻', '芸豆', '苹果', '莳萝']
['玉米'

(9, [5.0, 4.0, 4.0, 3.0, 3.0, 2.0, 2.0, 1.0, 1.0, 1.0, 1.0])

# 包引用方法

In [17]:
import pandas as pd
#显示所有列
pd.set_option('display.max_columns', None)
#显示所有行
pd.set_option('display.max_rows', None)
#设置value的显示长度为100，默认为50
pd.set_option('max_colwidth',100)
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori

#设置数据集
records = [['牛奶','洋葱','肉豆蔻','芸豆','鸡蛋','酸奶'],
        ['莳萝','洋葱','肉豆蔻','芸豆','鸡蛋','酸奶'],
        ['牛奶','苹果','芸豆','鸡蛋'],
        ['牛奶','独角兽','玉米','芸豆','酸奶'],
        ['玉米','洋葱','洋葱','芸豆','冰淇淋','鸡蛋']]
		
te = TransactionEncoder()
#进行 one-hot 编码
te_ary = te.fit(records).transform(records)
df = pd.DataFrame(te_ary, columns=te.columns_)
#利用 Apriori 找出频繁项集
freq = apriori(df, min_support=0.6, use_colnames=True)


In [18]:
te_ary

array([[False,  True,  True, False, False,  True,  True, False, False,
         True,  True],
       [False,  True, False, False, False,  True,  True, False,  True,
         True,  True],
       [False, False,  True, False, False, False,  True,  True, False,
        False,  True],
       [False, False,  True,  True,  True, False,  True, False, False,
         True, False],
       [ True,  True, False, False,  True, False,  True, False, False,
        False,  True]])

In [19]:
freq.sort_values(by="support" , ascending=False)

support      itemsets
2       1.0          (芸豆)
4       0.8          (鸡蛋)
9       0.8      (鸡蛋, 芸豆)
0       0.6          (洋葱)
1       0.6          (牛奶)
3       0.6          (酸奶)
5       0.6      (芸豆, 洋葱)
6       0.6      (鸡蛋, 洋葱)
7       0.6      (牛奶, 芸豆)
8       0.6      (芸豆, 酸奶)
10      0.6  (鸡蛋, 洋葱, 芸豆)