In [15]:
import numpy as np
import pandas as pd

In [16]:
def sigmoid(z):
    return 1/(1+np.exp(-z))

In [17]:
def forward(inputX,w0,w1): 
    l1 = sigmoid(np.dot(inputX,w0))
    l2 = sigmoid(np.dot(l1,w1))
    return l1,l2

In [18]:
def back(l1,l2,y,w1):
    error = y-l2
    slope = l2 * ( 1 - l2 )
    l1_delta = error*slope
    l0_slope = l1 * ( 1 - l1 )
    l0_error = l1_delta.dot(w1.T)
    l0_delta = l0_slope * l0_error
    return l0_delta , l1_delta 

In [19]:
def ReLU(a,Inactive):
    return (a.max() >= Inactive) and  a.max() or 0

In [20]:
def netWork(X,y,maxloop,newX,neurons = 8):
    m,n = X.shape
    np.random.seed(1)
    w0 = np.random.random((n,neurons)) * 2 -1
    w1 = np.random.random((neurons,1)) * 2 -1
    print('w:',w0,w1)
    for it in range(maxloop):
        l0 = X
        l1,l2 = forward(l0,w0,w1)
        l0delta,l1delta = back(l1,l2,y,w1)
        w1 = w1 +  np.dot(l1.T,l1delta)
        w0 = w0 +  np.dot(l0.T,l0delta)
    theta,fit = forward(newX,w0,w1)
    return ReLU(fit,0.5),fit,theta

In [21]:
X = np.array([[0,0,1],[0,1,1],[1,0,1],[1,1,1],[0,0,0]])
y = np.array([[0,1,1,0,0]]).T
X,y

(array([[0, 0, 1],
        [0, 1, 1],
        [1, 0, 1],
        [1, 1, 1],
        [0, 0, 0]]), array([[0],
        [1],
        [1],
        [0],
        [0]]))

In [22]:
netWork(X,y,10000,[[0,1,1]])

w: [[-0.16595599  0.44064899 -0.99977125 -0.39533485 -0.70648822 -0.81532281
  -0.62747958 -0.30887855]
 [-0.20646505  0.07763347 -0.16161097  0.370439   -0.5910955   0.75623487
  -0.94522481  0.34093502]
 [-0.1653904   0.11737966 -0.71922612 -0.60379702  0.60148914  0.93652315
  -0.37315164  0.38464523]] [[ 0.7527783 ]
 [ 0.78921333]
 [-0.82991158]
 [-0.92189043]
 [-0.66033916]
 [ 0.75628501]
 [-0.80330633]
 [-0.15778475]]


(0.9912533735486897,
 array([[0.99125337]]),
 array([[0.64217498, 0.55220843, 0.05681993, 0.10752063, 0.08415114,
         0.83448446, 0.03348754, 0.73228434]]))

In [23]:
from PIL import Image
import numpy as np
# import scipy

def loadImage():
    # 读取图片
    im = Image.open("测试图片.jpg")
    # 显示图片
    #im.show() 
    im = im.convert("L") 
    data = im.getdata()
    data = np.matrix(data)
    # 变换成512*512
    data = np.reshape(data,(512,512))
    #new_im = Image.fromarray(data)
    #new_im.show()
    return data

SRC = np.array(loadImage())
SrcX , SrcY = SRC[:,0:10],(SRC[:,-1]>50).astype(int)[:,None]
SrcY.shape,SrcX[10],SrcY[10]
SrcX.shape,SrcY.shape

((512, 10), (512, 1))

In [24]:
netWork(SrcX,SrcY,1,[[155, 155, 156, 158, 158, 154, 150, 150, 158, 156]],neurons=20)

w: [[-0.16595599  0.44064899 -0.99977125 -0.39533485 -0.70648822 -0.81532281
  -0.62747958 -0.30887855 -0.20646505  0.07763347 -0.16161097  0.370439
  -0.5910955   0.75623487 -0.94522481  0.34093502 -0.1653904   0.11737966
  -0.71922612 -0.60379702]
 [ 0.60148914  0.93652315 -0.37315164  0.38464523  0.7527783   0.78921333
  -0.82991158 -0.92189043 -0.66033916  0.75628501 -0.80330633 -0.15778475
   0.91577906  0.06633057  0.38375423 -0.36896874  0.37300186  0.66925134
  -0.96342345  0.50028863]
 [ 0.97772218  0.49633131 -0.43911202  0.57855866 -0.79354799 -0.10421295
   0.81719101 -0.4127717  -0.42444932 -0.73994286 -0.96126608  0.35767107
  -0.57674377 -0.46890668 -0.01685368 -0.89327491  0.14823521 -0.70654285
   0.17861107  0.39951672]
 [-0.79533114 -0.17188802  0.38880032 -0.17164146 -0.90009308  0.07179281
   0.32758929  0.02977822  0.88918951  0.17311008  0.80680383 -0.72505059
  -0.72144731  0.61478258 -0.20464633 -0.66929161  0.85501716 -0.30446828
   0.50162421  0.45199597]
 [ 

(1.0, array([[1.]]), array([[1.00000000e+000, 1.00000000e+000, 6.47947094e-078,
         7.67473557e-110, 4.48903287e-182, 0.00000000e+000,
         5.02572342e-225, 1.00000000e+000, 1.00000000e+000,
         1.00000000e+000, 7.09515833e-274, 1.00000000e+000,
         1.00000000e+000, 0.00000000e+000, 0.00000000e+000,
         1.00000000e+000, 0.00000000e+000, 1.00000000e+000,
         1.00000000e+000, 1.00000000e+000]]))

neurons = 8
m,n = X.shape
print(m,n)
np.random.seed(1)
w0 = np.random.random((n,neurons)) * 2 -1
w1 = np.random.random((neurons,1)) * 2 -1
for it in range(10000):
    l0 = X
    l1,l2 = fp(l0)
    l0delta,l1delta = bp(l1,l2,y)
    w1 = w1 +  np.dot(l1.T,l1delta)
    w0 = w0 +  np.dot(l0.T,l0delta)
fp([[0,1,1]])[1]

In [25]:
newX = np.array([[ 0.46371542, -0.41322646, -0.45222673, -0.38599564, -0.32291356,
        -0.45219767],
       [ 2.28173097, -0.38806597, -0.45222854, -0.3370525 , -0.22275721,
        -0.4521216 ],
       [ 0.2996969 , -0.41861615, -0.45222643, -0.39366509, -0.34002889,
        -0.45212794],
       [ 1.82023275, -0.39682214, -0.45222844, -0.34529062, -0.25762177,
        -0.45217865],
       [ 4.33961252, -0.36144667, -0.45222883, -0.29277167, -0.13718058,
        -0.45219133],
       [ 1.51683795, -0.40128883, -0.45222831, -0.35143702, -0.26649638,
        -0.45221034],
       [ 0.40860161, -0.41922005, -0.45222719, -0.39413959, -0.33559158,
        -0.45196312],
       [ 1.36927091, -0.399483  , -0.45222812, -0.35917707, -0.26713028,
        -0.45219767],
       [ 0.9242413 , -0.41331798, -0.45222807, -0.37214566, -0.31277115,
        -0.45219133],
       [ 3.03782194, -0.3810696 , -0.45222872, -0.31672937, -0.19359777,
        -0.45221034],
       [ 2.98947864, -0.38174535, -0.45222872, -0.31777699, -0.19613337,
        -0.45221034],
       [ 3.44414263, -0.39102372, -0.45222898, -0.3336006 , -0.22529282,
        -0.45222302]])
newy = np.array([0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0])[:,None]
newy.shape,newX.shape

((12, 1), (12, 6))

In [26]:
netWork(newX,newy,2,[[ 3.44414263, -0.39102372, -0.45222898, -0.3336006 , -0.22529282,
        -0.45222302]])

w: [[-0.16595599  0.44064899 -0.99977125 -0.39533485 -0.70648822 -0.81532281
  -0.62747958 -0.30887855]
 [-0.20646505  0.07763347 -0.16161097  0.370439   -0.5910955   0.75623487
  -0.94522481  0.34093502]
 [-0.1653904   0.11737966 -0.71922612 -0.60379702  0.60148914  0.93652315
  -0.37315164  0.38464523]
 [ 0.7527783   0.78921333 -0.82991158 -0.92189043 -0.66033916  0.75628501
  -0.80330633 -0.15778475]
 [ 0.91577906  0.06633057  0.38375423 -0.36896874  0.37300186  0.66925134
  -0.96342345  0.50028863]
 [ 0.97772218  0.49633131 -0.43911202  0.57855866 -0.79354799 -0.10421295
   0.81719101 -0.4127717 ]] [[-0.42444932]
 [-0.73994286]
 [-0.96126608]
 [ 0.35767107]
 [-0.57674377]
 [-0.46890668]
 [-0.01685368]
 [-0.89327491]]


(0,
 array([[0.34631114]]),
 array([[0.21902871, 0.71756283, 0.03996752, 0.25155977, 0.09981807,
         0.01844503, 0.18254577, 0.22054567]]))