In [1]:
import numpy as np
import pandas as pd

## 这是一个敌方间谍网络约定的红黄蓝信号灯的二进制码表我方观测到的结果，每一个行最后一个数字是布尔型的确认值，表示信号是一个单位曾经发送过的，预估一下这个单位的信号发送偏好
### $ X矩阵里的X_1 到 X_3 分别是三个红灯是否激发的标志 $
### $ y 向量则是敌方是否发现自己暴露的标志 1为敌人已经发现自己暴露，0为敌人尚未发现自己暴露$

## 处理数据，拿到X和y

In [2]:
X = np.array([[1,0,1],[1,1,0],[0,0,1],[0,1,0]])
X

array([[1, 0, 1],
       [1, 1, 0],
       [0, 0, 1],
       [0, 1, 0]])

In [3]:
y = np.array([[1],[1],[1],[0]])
y

array([[1],
       [1],
       [1],
       [0]])

## 随机生成每次相同的初始参数值

In [4]:
m,n = X.shape
np.random.seed(1)
weights = 2 * np.random.random((n,1))-1
weights

array([[-0.16595599],
       [ 0.44064899],
       [-0.99977125]])

In [5]:
for it in range(100):
    output = 1/(1+np.exp(-np.dot(X,weights)))
    error = y-output
    delta = error*output*(1-output) #sigmoid 函数的斜率 output*(1-output) 是斜率
    weights += np.dot(X.T,delta)
weights

array([[ 3.70721794],
       [-1.72281165],
       [ 2.42327552]])

## 验证数据的合理性
## 新拿到一组灯信号的组合方式，判断敌人是否发现自己暴露

In [6]:
1/(1+np.exp(-np.dot([[0,0,1]],weights)))

array([[0.91858505]])

## 整理一下代码

In [7]:
def sigmoid(z):
    return 1/(1+np.exp(-z))

def startweights():
    m,n = X.shape
    np.random.seed(1)
    return 2 * np.random.random((n,1))-1 

def network(X,y,maxloop,weights=startweights()):
    for it in range(maxloop):
        output = sigmoid(np.dot(X,weights))
        error = y-output
        delta = error*output*(1-output) 
        weights += np.dot(X.T,delta)
    return weights

def ReLU(a,Inactive):
    return (a.max() >= Inactive) and  a.max() or 0

def fit(newX,X,y,maxloop): 
    fitV = sigmoid(np.dot(newX,network(X,y,maxloop)))[:,0]
    return ReLU(fitV,0.5),fitV

In [8]:
fit([[1,1,0]],X,y,10000)

(0.9897718454498384, array([0.98977185]))

In [9]:
from PIL import Image
import numpy as np
# import scipy

def loadImage():
    # 读取图片
    im = Image.open("测试图片.jpg")
    # 显示图片
    #im.show() 
    im = im.convert("L") 
    data = im.getdata()
    data = np.matrix(data)
    # 变换成512*512
    data = np.reshape(data,(512,512))
    #new_im = Image.fromarray(data)
    #new_im.show()
    return data

loadImage()

matrix([[162, 161, 161, ..., 170, 154, 129],
        [161, 161, 161, ..., 173, 155, 125],
        [161, 161, 162, ..., 170, 155, 128],
        ...,
        [ 43,  42,  51, ..., 103, 101,  98],
        [ 40,  41,  55, ..., 102, 104, 106],
        [ 41,  43,  57, ..., 101, 106, 109]])