In [1]:
import torch
import numpy as np
import matplotlib.pyplot as plt

https://www.jianshu.com/p/5460b7fa3ec4

In [2]:
from torchvision.datasets import KMNIST

### numpy转tensor张量

In [10]:
x = np.arange(20).reshape(4,5)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [12]:
sub_ts = torch.from_numpy(x)
sub_ts

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])

### 张量转numpy

In [13]:
sub_np1 = sub_ts.numpy()
sub_np1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [1]:
import torch

x = torch.unsqueeze(torch.linspace(-100, 100, 1000), dim=1)
# 生成-100到100的1000个数的等差数列
y = 2*x + 1
# 定义y=2x+1函数
matrix = torch.nn.Linear(1, 1)
# 定义一个1x1的矩阵
optimizer = torch.optim.Adam(matrix.parameters(), lr=0.1)
# 使用优化器求导更新矩阵权重

for _ in range(100):
    # 训练100次
    value = matrix(x)
    # value是x与矩阵相乘后的值
    score = torch.mean((value - y) ** 2)
    # 目标偏差，值为(value-y)的平方取均值，越接近0说明结果越准确
    matrix.zero_grad()
    score.backward()
    optimizer.step()
    # 根据求导结果更新权值
    print("第{}次训练权值结果:{}，结果偏差：{}".format(_, matrix.weight.data.numpy(), score))

# 输出结果：
# 第0次训练权值结果:[[0.9555]]，结果偏差：4377.27294921875
# ...
# 第99次训练权值结果:[[2.0048]]，结果偏差：0.10316929966211319

第0次训练权值结果:[[0.9640945]]，结果偏差：4309.81689453125
第1次训练权值结果:[[1.0637488]]，结果偏差：3584.33642578125
第2次训练权值结果:[[1.1627736]]，结果偏差：2927.839111328125
第3次训练权值结果:[[1.260838]]，结果偏差：2341.220458984375
第4次训练权值结果:[[1.3575592]]，结果偏差：1824.864501953125
第5次训练权值结果:[[1.4524978]]，结果偏差：1378.5235595703125
第6次训练权值结果:[[1.545155]]，结果偏差：1001.1969604492188
第7次训练权值结果:[[1.6349729]]，结果偏差：691.0033569335938
第8次训练权值结果:[[1.7213384]]，结果偏差：445.0605773925781
第9次训练权值结果:[[1.8035934]]，结果偏差：259.39306640625
第10次训练权值结果:[[1.8810521]]，结果偏差：128.8842315673828
第11次训练权值结果:[[1.9530253]]，结果偏差：47.30034637451172
第12次训练权值结果:[[2.0188518]]，结果偏差：7.41132926940918
第13次训练权值结果:[[2.0779338]]，结果偏差：1.2216793298721313
第14次训练权值结果:[[2.1297743]]，结果偏差：20.312206268310547
第15次训练权值结果:[[2.1740084]]，结果偏差：56.26748275756836
第16次训练权值结果:[[2.210426]]，结果偏差：101.14115905761719
第17次训练权值结果:[[2.2389846]]，结果偏差：147.89634704589844
第18次训练权值结果:[[2.259806]]，结果偏差：190.76052856445312
第19次训练权值结果:[[2.2731655]]，结果偏差：225.4475555419922
第20次训练权值结果:[[2.2794712]]，结果偏差：249.23069763183594
第21

In [2]:
%lsmagic

Available line magics:
%alias  %alias_magic  %autocall  %automagic  %autosave  %bookmark  %cat  %cd  %clear  %colors  %config  %connect_info  %cp  %debug  %dhist  %dirs  %doctest_mode  %ed  %edit  %env  %gui  %hist  %history  %killbgscripts  %ldir  %less  %lf  %lk  %ll  %load  %load_ext  %loadpy  %logoff  %logon  %logstart  %logstate  %logstop  %ls  %lsmagic  %lx  %macro  %magic  %man  %matplotlib  %mkdir  %more  %mv  %notebook  %page  %pastebin  %pdb  %pdef  %pdoc  %pfile  %pinfo  %pinfo2  %popd  %pprint  %precision  %profile  %prun  %psearch  %psource  %pushd  %pwd  %pycat  %pylab  %qtconsole  %quickref  %recall  %rehashx  %reload_ext  %rep  %rerun  %reset  %reset_selective  %rm  %rmdir  %run  %save  %sc  %set_env  %store  %sx  %system  %tb  %time  %timeit  %unalias  %unload_ext  %who  %who_ls  %whos  %xdel  %xmode

Available cell magics:
%%!  %%HTML  %%SVG  %%bash  %%capture  %%debug  %%file  %%html  %%javascript  %%js  %%latex  %%markdown  %%perl  %%prun  %%pypy  %%python  %%python

In [4]:
?torch.optim

Type:        module
String form: <module 'torch.optim' from '/Users/manmanzhang/opt/anaconda3/envs/deeplearning/lib/python3.5/site-packages/torch/optim/__init__.py'>
File:        ~/opt/anaconda3/envs/deeplearning/lib/python3.5/site-packages/torch/optim/__init__.py
Docstring:  
:mod:`torch.optim` is a package implementing various optimization algorithms.
Most commonly used methods are already supported, and the interface is general
enough, so that more sophisticated ones can be also easily integrated in the
future.
