In [111]:
import numpy as np
import pandas as pd

In [112]:
X = np.array([[0,0,1],[1,1,1],[1,0,1],[0,1,1]])
X

array([[0, 0, 1],
       [1, 1, 1],
       [1, 0, 1],
       [0, 1, 1]])

In [113]:
Y = np.array([[0],[1],[1],[0]])
Y

array([[0],
       [1],
       [1],
       [0]])

In [114]:
def sigmoid(z):
    return 1/(1+np.exp(-z))

### 前向传播

In [115]:
def fp(X,weights): 
    z = -np.dot(X,weights)
    return sigmoid(z)

### 反项传播

In [116]:
def bp(y,output):
    error = y-output
    '''斜率或者导数'''
    slope = output*(1-output)
    return error*slope

### 初始化参数

In [117]:
def startWeights():
    m,n = X.shape
    np.random.seed(1)
    return 2 * np.random.random((n,1))-1 

In [118]:
def network(X,y,newX):
    weights =  startWeights()
    for it in range(10000):
        output = fp(X,weights)
        delta = bp(y,output)
        weights = weights +  np.dot(X.T,delta)
    return format(float(fp(newX,weights)),'.5f'),weights,fp(newX,weights)

In [119]:
network(X,Y,np.array([[0,0,1]]) )

('0.99991',
 array([[ 0.6231004 ],
        [-1.90655099],
        [-9.36811556]]),
 array([[0.9999146]]))

# 上面这种一个神经元的神经网络的限制是，一个神经元，只能解决线性关系，无法解决「异或关系」