In [ ]:
import numpy as np

# 数据降维

In [ ]:
data = np.random.sample(25).reshape(5,5)
data

### ravel（）：将多维数组拉平（一维

In [3]:
ravel_data  = data.ravel()
ravel_data.shape,ravel_data

((25,),
 array([0.18649757, 0.29237399, 0.58509222, 0.54510117, 0.37490166,
        0.20775867, 0.85581441, 0.4105886 , 0.17944988, 0.77170904,
        0.81442329, 0.36202312, 0.21916587, 0.18036198, 0.88763079,
        0.09028589, 0.42987495, 0.51014615, 0.66066771, 0.77963908,
        0.88643493, 0.92678445, 0.53231555, 0.90859962, 0.72073564]))

### flatten（）：将多维数组拉平，并拷贝一份

In [4]:
data = np.random.sample(25).reshape(5,5)
flatten_data  = data.flatten()
flatten_data.shape,flatten_data,data

((25,),
 array([0.20942935, 0.17581654, 0.44319106, 0.31029511, 0.94056989,
        0.95059799, 0.98693219, 0.69740365, 0.39118591, 0.18458124,
        0.61969717, 0.19585185, 0.81275703, 0.05781043, 0.1909073 ,
        0.71683451, 0.23418919, 0.48037881, 0.88687435, 0.74391817,
        0.34058106, 0.66231198, 0.9390865 , 0.22934223, 0.17320936]),
 array([[0.20942935, 0.17581654, 0.44319106, 0.31029511, 0.94056989],
        [0.95059799, 0.98693219, 0.69740365, 0.39118591, 0.18458124],
        [0.61969717, 0.19585185, 0.81275703, 0.05781043, 0.1909073 ],
        [0.71683451, 0.23418919, 0.48037881, 0.88687435, 0.74391817],
        [0.34058106, 0.66231198, 0.9390865 , 0.22934223, 0.17320936]]))

### squeeze（）

In [5]:
data = np.random.sample(25)[:,None]
data,np.squeeze(data)

(array([[0.97917812],
        [0.13892362],
        [0.10398234],
        [0.49306868],
        [0.07606387],
        [0.45136543],
        [0.96658451],
        [0.09141648],
        [0.45686105],
        [0.88096246],
        [0.38392692],
        [0.78433091],
        [0.05726751],
        [0.38695177],
        [0.53607228],
        [0.63012438],
        [0.65716081],
        [0.5188168 ],
        [0.99950264],
        [0.54053806],
        [0.16373098],
        [0.02414993],
        [0.41694845],
        [0.20364878],
        [0.25510467]]),
 array([0.97917812, 0.13892362, 0.10398234, 0.49306868, 0.07606387,
        0.45136543, 0.96658451, 0.09141648, 0.45686105, 0.88096246,
        0.38392692, 0.78433091, 0.05726751, 0.38695177, 0.53607228,
        0.63012438, 0.65716081, 0.5188168 , 0.99950264, 0.54053806,
        0.16373098, 0.02414993, 0.41694845, 0.20364878, 0.25510467]))

### reshape（-1）：多维数组，拉平

In [6]:
data.reshape(-1,25)

array([[0.97917812, 0.13892362, 0.10398234, 0.49306868, 0.07606387,
        0.45136543, 0.96658451, 0.09141648, 0.45686105, 0.88096246,
        0.38392692, 0.78433091, 0.05726751, 0.38695177, 0.53607228,
        0.63012438, 0.65716081, 0.5188168 , 0.99950264, 0.54053806,
        0.16373098, 0.02414993, 0.41694845, 0.20364878, 0.25510467]])