In [28]:
import torch

## where函数

In [29]:
cond = torch.rand(10).reshape(2,5).T
a = torch.zeros(10).reshape(2,5).T
b = torch.ones(10).reshape(2,5).T

In [30]:
a,b,cond

(tensor([[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]]),
 tensor([[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]]),
 tensor([[0.3121, 0.3069],
         [0.9294, 0.5010],
         [0.9739, 0.6194],
         [0.7536, 0.3758],
         [0.5175, 0.4614]]))

In [31]:
torch.where(cond>0.5,b,a)

tensor([[0., 0.],
        [1., 1.],
        [1., 1.],
        [1., 0.],
        [1., 0.]])

## gather 收集函数

In [32]:
table = torch.Tensor(['dog','cat','whell'])

ValueError: too many dimensions 'str'

In [33]:
prob = torch.randn(4,10)
prob

tensor([[ 1.0513, -0.2772, -0.7542,  1.2767,  2.2565, -0.0973, -0.3973,  0.4521,
         -1.4197, -1.1632],
        [-0.1986,  1.0548, -0.3634, -2.0970,  1.0908,  0.5647,  0.1142, -0.1241,
          0.4667, -0.7398],
        [ 0.4075, -0.5110, -0.6078,  0.3151,  0.3472, -0.0765, -0.3105, -1.2856,
          1.7716,  1.0432],
        [ 1.9569,  0.2987, -0.8352, -0.2443, -0.8445,  1.1098,  0.6245,  0.2825,
          1.3719, -2.5992]])

In [34]:
idx = prob.topk(dim=1,k=3)#k选择最有可能的几种情况
idx

torch.return_types.topk(
values=tensor([[2.2565, 1.2767, 1.0513],
        [1.0908, 1.0548, 0.5647],
        [1.7716, 1.0432, 0.4075],
        [1.9569, 1.3719, 1.1098]]),
indices=tensor([[4, 3, 0],
        [4, 1, 5],
        [8, 9, 0],
        [0, 8, 5]]))

In [35]:
idx=idx[1]
idx

tensor([[4, 3, 0],
        [4, 1, 5],
        [8, 9, 0],
        [0, 8, 5]])

In [36]:
label = torch.arange(10)+100
label

tensor([100, 101, 102, 103, 104, 105, 106, 107, 108, 109])

In [37]:
label.expand(4,10) #全局表复制四次

tensor([[100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
        [100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
        [100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
        [100, 101, 102, 103, 104, 105, 106, 107, 108, 109]])

In [38]:
torch.gather(label.expand(4,10),dim=1,index=idx.long())

tensor([[104, 103, 100],
        [104, 101, 105],
        [108, 109, 100],
        [100, 108, 105]])

## 梯度其实就是偏微分组合的向量(每一个轴是每一个轴组合的偏微分)
## $ z=y2-x2 $
## $ \partial z / \partial x = -2x $
## $ \partial z / \partial y = 2y $