In [1]:
from __future__ import print_function
import torch
#构造一个5×3矩阵，不初始化。

x = torch.empty(5, 3)
x

tensor([[1.4569e-19, 6.7421e+22, 6.4610e+19],
        [2.0618e-19, 1.8545e+25, 6.9767e+22],
        [5.0850e+31, 6.4600e+19, 1.8888e+31],
        [1.6581e+25, 1.8611e+34, 1.9005e-19],
        [1.0999e-32, 1.3563e-19, 7.2127e+22]])

# 构造一个随机初始化的矩阵：

In [2]:
x = torch.rand(5, 3)
x

tensor([[0.8086, 0.1484, 0.6253],
        [0.6596, 0.1254, 0.1727],
        [0.8466, 0.2532, 0.0372],
        [0.9924, 0.1261, 0.0618],
        [0.0305, 0.3132, 0.8291]])

# 构造一个矩阵全为 0，而且数据类型是 long.
#Construct a matrix filled zeros and of dtype long:

In [5]:
x = torch.zeros(5, 3, dtype=torch.long)
x

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

# 构造一个张量，直接使用数据：

In [6]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


# 创建一个 tensor 基于已经存在的 tensor。

In [14]:
x = x.new_ones(5, 3, dtype=torch.double)
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [18]:
x = torch.randn_like(x, dtype=torch.float)
x

tensor([[ 0.5744,  0.0324, -0.0569],
        [ 0.7678,  0.2430, -0.0499],
        [-0.7561, -0.6234, -0.2322],
        [ 1.0049, -1.0375,  0.9175],
        [-2.0694,  0.5427, -0.6764]])

# 获取它的维度信息:

In [20]:
xsize =x.size()
m,n= xsize
xsize,m,n

(torch.Size([5, 3]), 5, 3)

# 加法:

In [26]:
y = torch.rand(5,3)
y

tensor([[0.5352, 0.3723, 0.9230],
        [0.8223, 0.4149, 0.8590],
        [0.8955, 0.6095, 0.7083],
        [0.0465, 0.4798, 0.0076],
        [0.4696, 0.1007, 0.7653]])

In [27]:
x+y

tensor([[ 1.1095,  0.4048,  0.8660],
        [ 1.5900,  0.6579,  0.8091],
        [ 0.1394, -0.0139,  0.4761],
        [ 1.0513, -0.5577,  0.9251],
        [-1.5998,  0.6434,  0.0889]])

In [28]:
torch.add(x,y)

tensor([[ 1.1095,  0.4048,  0.8660],
        [ 1.5900,  0.6579,  0.8091],
        [ 0.1394, -0.0139,  0.4761],
        [ 1.0513, -0.5577,  0.9251],
        [-1.5998,  0.6434,  0.0889]])

# 加法: 提供一个输出 tensor 作为参数

In [29]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)

tensor([[ 1.1095,  0.4048,  0.8660],
        [ 1.5900,  0.6579,  0.8091],
        [ 0.1394, -0.0139,  0.4761],
        [ 1.0513, -0.5577,  0.9251],
        [-1.5998,  0.6434,  0.0889]])

In [34]:
y.add_(x)
y

tensor([[ 1.1095,  0.4048,  0.8660],
        [ 1.5900,  0.6579,  0.8091],
        [ 0.1394, -0.0139,  0.4761],
        [ 1.0513, -0.5577,  0.9251],
        [-1.5998,  0.6434,  0.0889]])

# 任何使张量会发生变化的操作都有一个前缀 ‘_’。例如：x.copy_(y), x.t_(), 将会改变 x.你可以使用标准的  NumPy 类似的索引操作

In [38]:
x[:,:1]

tensor([[ 0.5744],
        [ 0.7678],
        [-0.7561],
        [ 1.0049],
        [-2.0694]])

In [40]:
x.t_()

tensor([[ 0.5744,  0.7678, -0.7561,  1.0049, -2.0694],
        [ 0.0324,  0.2430, -0.6234, -1.0375,  0.5427],
        [-0.0569, -0.0499, -0.2322,  0.9175, -0.6764]])

# 改变大小：如果你想改变一个 tensor 的大小或者形状，你可以使用 torch.view:

In [41]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
x.size(), y.size(), z.size()

(torch.Size([4, 4]), torch.Size([16]), torch.Size([2, 8]))

In [42]:
x

tensor([[ 0.6241, -1.7628, -0.3089, -0.7421],
        [ 1.2275,  0.0935, -0.4188, -0.9336],
        [ 1.9370,  1.1478, -1.5731, -2.7789],
        [-1.1168,  2.1390, -0.4523,  1.0072]])

In [43]:
y

tensor([ 0.6241, -1.7628, -0.3089, -0.7421,  1.2275,  0.0935, -0.4188, -0.9336,
         1.9370,  1.1478, -1.5731, -2.7789, -1.1168,  2.1390, -0.4523,  1.0072])

In [44]:
z

tensor([[ 0.6241, -1.7628, -0.3089, -0.7421,  1.2275,  0.0935, -0.4188, -0.9336],
        [ 1.9370,  1.1478, -1.5731, -2.7789, -1.1168,  2.1390, -0.4523,  1.0072]])

In [49]:
x.view(8,2)

tensor([[ 0.6241, -1.7628],
        [-0.3089, -0.7421],
        [ 1.2275,  0.0935],
        [-0.4188, -0.9336],
        [ 1.9370,  1.1478],
        [-1.5731, -2.7789],
        [-1.1168,  2.1390],
        [-0.4523,  1.0072]])