In [61]:
import numpy as np
import scipy
from scipy import stats

## $ N(\mu ,\sigma^2) $
## $ \mu 是分布期望 , \sigma^2 是方差 $

## 高斯分布函数
## $ P_G(z) = (1 /(\sigma\sqrt{2\pi})^e)^{-(z-\mu)^2/(2\sigma)^2} $

In [62]:
# 给数据加指定SNR的高斯噪声
signal = np.arange(100).reshape(2,50)
SNR = 5
noise = np.random.randn(signal.shape[0],signal.shape[1]) 	#产生N(0,1)噪声数据
noise = noise-np.mean(noise) 								#均值为0
signal_power = np.linalg.norm( signal )**2 / signal.size	#此处是信号的std**2
noise_variance = signal_power/np.power(10,(SNR/10))         #此处是噪声的std**2
noise = (np.sqrt(noise_variance) / np.std(noise) )*noise    ##此处是噪声的std**2
signal_noise = noise + signal

Ps = ( np.linalg.norm(signal - signal.mean()) )**2          #signal power
Pn = ( np.linalg.norm(signal - signal_noise ) )**2          #noise power
snr = 10*np.log10(Ps/Pn)

In [63]:
snr

-0.9556169829104516

$ noise = std * N(0,1) + mean $

In [64]:
x = np.random.random(100).reshape(2,50).T
y = np.random.random(50)[:,None]

In [77]:
np.random.seed(0)
w = np.random.random(x.shape[1])[:,None]
b = np.random.random(1)[:,None]
w,b

(array([[0.5488135 ],
        [0.71518937]]),
 array([[0.60276338]]))

In [74]:
x.dot(w)

array([[0.3622001 ],
       [0.33902189],
       [0.90754348],
       [0.59654181],
       [0.5080954 ],
       [0.77937912],
       [0.73770341],
       [0.16241269],
       [0.8719145 ],
       [0.20825797],
       [0.75911217],
       [0.37779207],
       [0.38028819],
       [0.71721665],
       [0.77531608],
       [0.95503061],
       [0.84352393],
       [1.06971217],
       [0.6582827 ],
       [0.46887956],
       [0.78722815],
       [0.21187475],
       [0.39780443],
       [0.35897891],
       [1.04686105],
       [0.1685073 ],
       [0.68328124],
       [0.16013735],
       [0.06589015],
       [0.57422138],
       [0.84830069],
       [0.60638654],
       [0.45538264],
       [0.72045405],
       [0.65055656],
       [0.78649331],
       [0.72979818],
       [0.57507301],
       [0.22518932],
       [0.74342282],
       [0.31462509],
       [0.84722587],
       [1.00531634],
       [0.93611709],
       [0.54876801],
       [0.75154076],
       [0.29037073],
       [1.029

In [80]:
for i in range(10):
    w = 0.000001-1/2*x.shape[0]/((np.dot(x,w)+b-y)**2)
    print(w)

[[-2.97698723e+01 -1.24824377e+01]
 [-8.74960974e+00 -5.05342965e+01]
 [-2.54011943e+01 -2.50232580e+00]
 [-1.23019833e+01 -1.14388875e+01]
 [-2.62611544e+01 -8.07053015e+00]
 [-8.03155142e+00 -6.55890272e+00]
 [-3.07530251e+00 -2.12925707e+01]
 [-1.32001753e+05 -3.63880431e+03]
 [-8.61381543e+00 -3.20884484e+00]
 [-3.31817223e+03 -1.75313657e+03]
 [-3.29259136e+00 -6.11516233e+00]
 [-3.17233121e+01 -3.31107408e+02]
 [-6.68344179e+00 -3.55251164e+02]
 [-1.94875018e+02 -3.23201362e+00]
 [-1.03387272e+02 -2.10389940e+00]
 [-5.67681187e+00 -1.74423222e+00]
 [-1.45237932e+01 -2.32617194e+00]
 [-3.21397867e+00 -5.18802905e+00]
 [-3.81742772e+00 -2.41886138e+01]
 [-3.75801691e+00 -6.46119086e+02]
 [-2.50552455e+00 -1.29979954e+01]
 [-1.76491801e+02 -3.03579920e+01]
 [-9.23182835e+00 -1.14628121e+03]
 [-9.61967830e+00 -3.11665188e+02]
 [-2.40659212e+00 -4.41516997e+00]
 [-1.28224857e+01 -1.60696672e+02]
 [-1.26881643e+02 -4.58697511e+00]
 [-5.75368052e+01 -3.66710929e+01]
 [-2.43991334e+08 -4

ValueError: shapes (50,2) and (50,2) not aligned: 2 (dim 1) != 50 (dim 0)

In [ ]:
from selenium.webdriver import ChromeOptionsoption = ChromeOptions()option.add_experimental_option('excludeSwitches',['enable-automation'])#开启实验性功能
browser=webdriver.Chrome(options=option)# 修改get方法
script = '''Object.defineProperty(navigator, 'webdriver', {get: () => undefined})'''browser.execute_cdp_cmd("Page.addScriptToEvaluateOnNewDocument", {"source": script})